"""ORM model package - importing it registers every table on ``Base.metadata``."""

from app.models.admin import AdminAuditLog
from app.models.analytics import AnalyticsEvent, IdempotencyRecord
from app.models.container import Container, ContainerOpening
from app.models.enums import (
    AdminAction,
    AdminCategory,
    AnalyticsEventName,
    ChallengeStatus,
    EntitlementTier,
    GrantType,
    LeaderboardCategory,
    PaymentProvider,
    PaymentStatus,
    ReferralStatus,
    RollSource,
    TransactionType,
    UserRole,
)
from app.models.number import Discovery, Number, UserNumber
from app.models.numora import (
    AlbumProgress,
    Cosmetic,
    CosmeticTitle,
    GameEvent,
    Mission,
    PlateRoll,
    SeasonProgress,
    SupporterEntitlement,
    UserCosmetic,
    UserMission,
)
from app.models.payment import Payment, PremiumEntitlement, Product
from app.models.plates import (
    Album,
    Country,
    Plate,
    PlateAlbum,
    PlateChallenge,
    PlateDiscovery,
    PlateTemplate,
    Region,
    UserPlate,
)
from app.models.progression import Achievement, DailyReward, Season, UserAchievement
from app.models.roll import Roll
from app.models.social import Challenge, Referral, ShareEvent
from app.models.user import User, Wallet, WalletTransaction

__all__ = [
    "Achievement",
    "AdminAction",
    "AdminAuditLog",
    "AdminCategory",
    "Album",
    "AlbumProgress",
    "AnalyticsEvent",
    "AnalyticsEventName",
    "Challenge",
    "ChallengeStatus",
    "Container",
    "ContainerOpening",
    "Cosmetic",
    "CosmeticTitle",
    "Country",
    "DailyReward",
    "Discovery",
    "EntitlementTier",
    "GameEvent",
    "GrantType",
    "IdempotencyRecord",
    "LeaderboardCategory",
    "Mission",
    "Number",
    "Payment",
    "PaymentProvider",
    "PaymentStatus",
    "Plate",
    "PlateAlbum",
    "PlateChallenge",
    "PlateDiscovery",
    "PlateRoll",
    "PlateTemplate",
    "PremiumEntitlement",
    "Product",
    "Referral",
    "ReferralStatus",
    "Region",
    "Roll",
    "RollSource",
    "Season",
    "SeasonProgress",
    "ShareEvent",
    "SupporterEntitlement",
    "TransactionType",
    "User",
    "UserAchievement",
    "UserCosmetic",
    "UserMission",
    "UserNumber",
    "UserPlate",
    "UserRole",
    "Wallet",
    "WalletTransaction",
]
