import { useEffect, useMemo, useRef, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';

import { EASE, SPRING } from '@/lib/motion';
import { useT } from '@/i18n';
import type { ReelFrame } from '@/types';
import CollectibleVisualFrame from './CollectibleVisualFrame';

/**
 * The roll reel: a long stream of collectibles that scrolls and settles on one.
 *
 * ### What it is, and what it is not
 *
 * The frames are **synthetic previews generated by the backend and never persisted**.
 * They are not scored, not valued, not owned, and the reel never decides anything: the
 * real collectible is decided and committed *before* the response is built, and arrives
 * separately as the final card. A frame is a picture of a plate, nothing more.
 *
 * That is why the reel can be as fast, as long and as noisy as it likes. It cannot grant
 * anything, so making it entertaining costs the player nothing and the economy nothing.
 *
 * ### How the scroll works
 *
 * A vertical strip of frames inside a window that is exactly one object tall. The strip
 * is translated from `-0 items` down to `-items items`, so the last frame settles exactly
 * in the centre of the window and is the frame the player is left looking at.
 *
 * Everything is `transform` and `opacity` on pre-rendered, pre-transformed layers, so the
 * whole animation runs on the compositor with no layout and no paint. The easing is a
 * single long deceleration: quick at first, then a long bleed off, which is what reads
 * as physical momentum rather than as a loop.
 *
 * ### Containment
 *
 * The window is `overflow: hidden` and sized to exactly one object, and every frame is
 * given the object's own width. Nothing can escape it, and nothing inside it can push the
 * page sideways. The frame's own `PlateCard`-shaped renderer clips its printing to the
 * plate, so even a very long serial shrinks to fit rather than overflowing.
 */

/**
 * How long the scroll runs, in seconds.
 *
 * Long enough to read as a real search, short enough that the player is not waiting on an
 * animation they have already seen. Always skippable.
 */
const SCROLL_SECONDS = 2.4;

interface Props {
  /** Synthetic frames from the server. Must be non-empty for the reel to run. */
  frames: ReelFrame[];
  /** The real result, rendered as the frame the reel settles on. */
  final: React.ReactNode;
  /** The real result's text, used for the accessible label. */
  finalLabel: string;
  /** False until the reel has settled; drives the readout that follows. */
  settled: boolean;
  /** Fired when the strip reaches its final position. */
  onSettled?: () => void;
}

export function RollReel({ frames, final, finalLabel, settled, onSettled }: Props) {
  const t = useT();
  const reduced = useReducedMotion();

  /*
   * The strip's contents are computed once per frame list and never while it scrolls.
   *
   * This is the performance story of the whole reel: the frames arrive with the roll
   * response, so they exist before the first paint. Nothing is mounted during the
   * animation, nothing is unmounted after it, and the real card replaces the strip only
   * once the reel has landed.
   */
  const items = useMemo(() => frames, [frames]);
  /*
   * Whether the reel is still scrolling.
   *
   * The parent's `settled` flag is authoritative: once the reveal says the reel has
   * landed, the strip is gone and stays gone. The internal timer only *reports* the
   * landing, so the two can never disagree about which object the player is looking at.
   */
  const [done, setDone] = useState(() => settled);
  const reported = useRef(false);

  useEffect(() => {
    if (settled) {
      setDone(true);
      return undefined;
    }
    if (items.length === 0) {
      setDone(true);
      return undefined;
    }
    setDone(false);
    reported.current = false;
    const timer = window.setTimeout(() => {
      setDone(true);
      if (!reported.current) {
        reported.current = true;
        onSettled?.();
      }
    }, SCROLL_SECONDS * 1000);
    return () => window.clearTimeout(timer);
  }, [items.length, onSettled, settled]);

  // Nothing to scroll, or the player asked for less motion: the result simply appears.
  if (items.length === 0 || reduced || settled) return <>{final}</>;

  /*
   * Distance travelled.
   *
   * Every frame exactly once, plus a partial offset so the strip does not land on a
   * frame boundary - a reel that stops dead between two numbers reads as a glitch.
   */
  const travel = items.length + 0.35;

  return (
    <div className="flex w-full flex-col items-center gap-3">
      {/*
        The window. Exactly one object tall, clipped.

        The height comes from `--reel-row`, which is a `clamp()` in `vh`. A fixed pixel
        row looked right in portrait on one phone and pushed the roll button and the
        result straight off a landscape screen, where the whole app can be 360px tall.
        Scaling with the viewport is what makes the reel fit everywhere.
      */}
      <div
        className="reel-window"
        style={{ height: 'var(--reel-row)' }}
        role="status"
        aria-live="polite"
        aria-label={done ? finalLabel : t('reel.spinning')}
        data-testid="reel-window"
      >
        {!done ? (
          <motion.div
            className="reel-strip"
            style={{ height: `calc(var(--reel-row) * ${items.length})` }}
            initial={{ y: 0 }}
            animate={{ y: `calc(var(--reel-row) * -${travel})` }}
            transition={{ duration: SCROLL_SECONDS, ease: EASE.reel }}
            data-testid="reel-strip"
          >
            {items.map((item, index) => (
              <ReelRow key={`${item.plate_text}-${index}`} frame={item} />
            ))}
          </motion.div>
        ) : null}
      </div>

      {/*
        The result. Mounted only after the strip is gone, so the two never overlap and the
        player is never looking at two collectibles at once.
      */}
      {done ? (
        <motion.div
          className="flex w-full flex-col items-center"
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ ...SPRING.settle, duration: 0.34 }}
          data-testid="reel-result"
        >
          {final}
        </motion.div>
      ) : null}
    </div>
  );
}

/** One row of the strip: a full collectible object, at the reel's own scale. */
function ReelRow({ frame }: { frame: ReelFrame }) {
  return (
    <div
      className="reel-row"
      style={{ height: 'var(--reel-row)' }}
      data-testid="reel-frame"
      data-kind={frame.kind}
      data-country={frame.country_code}
      aria-hidden="true"
    >
      {/*
        A frame renders through the same components as the real card. A passing frame
        that looked even slightly different - a different band, a different proportion, a
        flat rectangle instead of a physical object - would give the game away.
      */}
      <div className="reel-object">
        <CollectibleVisualFrame
          visual={frame.visual}
          plateText={frame.plate_text}
          displaySegments={frame.display_segments}
          displaySegmentGaps={frame.display_segment_gaps}
          displaySegmentKinds={frame.display_segment_kinds}
          kind={frame.kind}
        />
      </div>
    </div>
  );
}

export { SCROLL_SECONDS };
export default RollReel;
