import { motion } from 'framer-motion';

import { useReducedMotion } from '../lib/motion';
import type { SimCardConfig, SimCardDetails } from '../types';

/**
 * A collectible SIM card: a physical plastic card with a printed operator brand, a
 * printed series, an edition and a contact module.
 *
 * Two things this component takes seriously.
 *
 * **The operator is real.** The brand comes from the server's provider catalogue, so a
 * card in Russia prints MTS, MegaFon, Beeline or T2 - the operators that actually
 * operate there. A card printed with a retired game brand is marked as such and never
 * claims to be a real carrier.
 *
 * **The number is synthetic.** It is information *printed on* a card, generated by the
 * backend. It is not a subscriber line, it is not a service, and the card says so: a
 * permanent `SYNTHETIC · GAME COLLECTIBLE` mark sits in the corner. The operator's real
 * tariffs, customers or finances are never implied - the brand influences the game's
 * rarity and value weighting and nothing else.
 *
 * ### The physical model
 *
 * An ID-1 SIM is 85.60 x 53.98 mm (ratio 1.586) of moulded PVC with:
 *
 * * a **clipped top-left corner** on a 45-degree bevel, not a rounded rectangle;
 * * a **gold contact module** - a chip pad with a notched centre, plus the four
 *   contact fingers printed below it on a full-size card;
 * * a **moulded edge**: a 1px bright rim with a dark inner line, which is what
 *   injection-moulded plastic actually looks like under a light;
 * * a **printed brand zone** with the operator's mark and wordmark;
 * * the **number**, grouped the way the country groups it;
 * * and fine surface wear, because a card that has been in a wallet is not pristine.
 */

interface Props {
  details: SimCardDetails | null;
  config?: SimCardConfig | null;
  rarity?: string;
  accent?: string;
  scale?: number;
  className?: string;
  /** Adds the reveal's idle float. Off inside lists so a page of cards stays still. */
  animate?: boolean;
}

/** Brand mark shapes, drawn as CSS so no image asset is needed at any density. */
function BrandMark({ visual, accent }: { visual: string; accent: string }) {
  const common = { background: accent } as const;
  switch (visual) {
    case 'waveform':
      return (
        <span
          aria-hidden="true"
          className="flex h-4 items-end gap-[2px]"
          style={{ opacity: 0.9 }}
        >
          {[6, 11, 16, 9].map((height, index) => (
            <span key={index} style={{ ...common, width: 2, height, borderRadius: 1 }} />
          ))}
        </span>
      );
    case 'burst':
      return (
        <span
          aria-hidden="true"
          className="h-4 w-4 rotate-45 rounded-[3px]"
          style={{ ...common, boxShadow: `0 0 10px ${accent}` }}
        />
      );
    case 'circle':
      return (
        <span
          aria-hidden="true"
          className="h-4 w-4 rounded-full border-2"
          style={{ borderColor: accent }}
        />
      );
    case 'globe':
      return (
        <span
          aria-hidden="true"
          className="h-4 w-4 rounded-full border"
          style={{ borderColor: accent }}
        >
          <span className="mx-auto mt-[3px] block h-px w-full" style={{ background: accent }} />
        </span>
      );
    case 'check':
      return (
        <span
          aria-hidden="true"
          className="h-4 w-4 rotate-45 rounded-tl-[3px] border-l-2 border-t-2"
          style={{ borderColor: accent }}
        />
      );
    case 'dots':
      return (
        <span aria-hidden="true" className="grid h-4 w-4 grid-cols-2 gap-[2px]">
          {[0, 1, 2, 3].map((index) => (
            <span key={index} className="rounded-full" style={{ ...common }} />
          ))}
        </span>
      );
    case 'blocks':
    default:
      return (
        <span aria-hidden="true" className="flex gap-[3px]">
          <span style={{ ...common, width: 6, height: 14, borderRadius: 2 }} />
          <span
            style={{ ...common, width: 6, height: 14, borderRadius: 2, opacity: 0.55 }}
          />
        </span>
      );
  }
}

export default function SimCardVisual({
  details,
  config,
  rarity,
  accent,
  scale = 1,
  className = '',
  animate = false,
}: Props) {
  const reduced = useReducedMotion();
  const brand = details?.operator ?? '';
  const brandAccent = details?.operator_accent || accent || '#c9a227';
  const number = details?.synthetic_number ?? '';
  const groups = config?.groups?.length ? config.groups : number.split(' ').slice(2).map((g) => g.length);

  return (
    <motion.div
      className={`sim-body ${className}`}
      style={{
        // 85.6mm at scale 1, matching the ID-1 standard the aspect ratio comes from.
        width: `${Math.round(85.6 * 3.85 * scale)}px`,
        maxWidth: '100%',
      }}
      initial={false}
      animate={animate && !reduced ? { y: [0, -4, 0] } : { y: 0 }}
      transition={
        animate && !reduced
          ? { duration: 3.6, repeat: Infinity, ease: 'easeInOut' }
          : { duration: 0.2 }
      }
      role="img"
      aria-label={`${brand} SIM card, number ${number}`}
      data-sim-operator={brand}
    >
      {/* The clipped corner. Drawn over the body with the page behind showing through,
          which is exactly how the moulded bevel catches light on a real card. */}
      <span className="sim-notch" aria-hidden="true" />

      {/* The operator's own identity stripe along the top edge. */}
      <span
        className="sim-brand-bar"
        style={{
          background: `linear-gradient(90deg, ${brandAccent}, ${brandAccent}22)`,
        }}
        aria-hidden="true"
      />

      {/* The contact module: the chip pad and, below it, the printed contact fingers. */}
      <span className="sim-contact" aria-hidden="true" />
      <span className="sim-pad" aria-hidden="true">
        <span />
        <span />
        <span />
        <span />
      </span>

      <span className="sim-sheen" aria-hidden="true" />

      <div className="relative z-10 flex w-full flex-col justify-between p-[6%] pl-[27%]">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <BrandMark visual={details?.operator_visual ?? 'neutral'} accent={brandAccent} />
              <span className="truncate font-display text-[clamp(11px,3.4cqw,19px)] font-bold leading-tight tracking-[-0.01em] text-white">
                {brand}
              </span>
            </div>
            {details?.operator_local && details.operator_local !== brand && (
              <span className="block truncate text-[clamp(8px,2.2cqw,12px)] text-white/45">
                {details.operator_local}
              </span>
            )}
          </div>
          {rarity ? (
            <span
              className="shrink-0 rounded-md border border-white/15 bg-white/5 px-1.5 py-0.5 text-[clamp(7px,1.9cqw,11px)] font-semibold uppercase tracking-[0.08em] text-white/70"
            >
              {rarity}
            </span>
          ) : null}
        </div>

        {/* The printed number, grouped the way the country groups it. */}
        <div className="my-[3%]">
          <span className="block font-mono text-[clamp(14px,5.6cqw,30px)] font-bold leading-tight tracking-[0.04em] text-white tabular-nums">
            {number}
          </span>
        </div>

        <div className="flex items-end justify-between gap-2">
          <div className="min-w-0">
            {details?.series && (
              <span className="block text-[clamp(8px,2.3cqw,13px)] font-semibold tracking-[0.1em] text-white/70">
                {details.series}
              </span>
            )}
            {details?.edition && (
              <span className="block text-[clamp(7px,1.9cqw,11px)] tracking-[0.1em] text-white/45">
                {details.edition}
              </span>
            )}
            {groups?.length ? (
              <span className="sr-only-number">{groups.join('-')}</span>
            ) : null}
          </div>
          {details?.calling_code && (
            <span className="shrink-0 text-[clamp(9px,2.5cqw,14px)] font-semibold text-white/60">
              {details.calling_code}
            </span>
          )}
        </div>

        {/* The synthetic marker. Always visible, never subtle enough to be missed. */}
        <span className="mt-[4%] block text-[clamp(6px,1.6cqw,9px)] uppercase tracking-[0.12em] text-white/35">
          Synthetic · game collectible
          {details?.operator_is_real === false ? ' · game brand' : ''}
        </span>
      </div>
    </motion.div>
  );
}
export { SimCardVisual };
