"""One-off generator for ``app/game/iso_countries.py``.

Reads the ``mledoze/countries`` ISO 3166-1 dataset and emits a frozen Python table
so the game ships the country list **in the repository** instead of downloading it
at runtime. Run manually when the ISO list changes:

    python -m scripts.gen_iso_table path/to/countries.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# ISO region -> NUMORA region group used by albums and the WORLD screen.
REGION_MAP = {
    "Europe": "EUROPE",
    "Americas": "AMERICAS",
    "Asia": "ASIA",
    "Africa": "AFRICA",
    "Oceania": "OCEANIA",
    "Antarctic": "ANTARCTIC",
}

# Western Asia is grouped with the Middle East so the existing MIDEAST events and
# albums keep working without a second taxonomy.
SUBREGION_MAP = {"Western Asia": "MIDEAST"}

#: Countries the game keeps in the historical CIS bucket. The source dataset groups
#: them by geography, but NUMORA's CIS album, tag and event are keyed on it, so the
#: value is authoritative here rather than derived.
REGION_OVERRIDES: dict[str, str] = {
    "RUS": "CIS",
    "BLR": "CIS",
    "UKR": "CIS",
    "MDA": "CIS",
    "ARM": "CIS",
    "GEO": "CIS",
    "KAZ": "CIS",
    "TKM": "CIS",
    "TJK": "CIS",
    "KGZ": "CIS",
    "UZB": "CIS",
}

#: Currency glyphs that read correctly in both game languages. Anything else (a
#: locale-specific Arabic, Hebrew or Indic sign) falls back to the ISO code so the
#: collector value never renders as an unreadable mark.
ALLOWED_SYMBOLS = frozenset(
    "$€£¥₽₹₩₺₴₸₦₪₾฿₫₱₡₴ƒ₺"
    "złKčFr.SFrCHFleiлвдинRMNZDKrsUShKShBrQAR₪SARJODKDHRILS₪"
    "krFtzłBYNPLNCZKRSUMDLTL₺"
)

#: Currencies whose dataset symbol is not usable; these keep a plain ISO code.
SYMBOL_BLACKLIST = frozenset(
    {"SYP", "IRR", "YER", "LBP", "IQD", "SDG", "LYD", "TND", "MRU", "ZWL", "VUV"}
)

# Fallback symbols for currencies the dataset does not carry a symbol for.
SYMBOLS = {
    "EUR": "€", "USD": "$", "GBP": "£", "JPY": "¥", "RUB": "₽", "CNY": "¥",
    "KRW": "₩", "INR": "₹", "BRL": "R$", "CAD": "C$", "AUD": "A$", "CHF": "CHF",
    "TRY": "₺", "ZAR": "R", "KZT": "₸", "UAH": "₴", "PLN": "zł", "SEK": "kr",
    "NOK": "kr", "DKK": "kr", "AED": "AED", "SAR": "SAR", "ILS": "₪",
    "GEL": "₾", "AMD": "֏", "THB": "฿", "VND": "₫", "IDR": "Rp", "MYR": "RM",
    "SGD": "S$", "HKD": "HK$", "NZD": "NZ$", "MXN": "Mex$", "ARS": "AR$",
    "CLP": "CLP$", "COP": "COL$", "PEN": "S/", "EGP": "E£", "NGN": "₦",
    "KES": "KSh", "PKR": "₨", "BDT": "৳", "LKR": "Rs", "MAD": "DH",
    "CZK": "Kč", "HUF": "Ft", "RON": "lei", "BGN": "лв", "HRK": "kn",
    "ISK": "kr", "RSD": "дин", "MNT": "₮", "KGS": "с", "TJS": "см",
    "TMT": "m", "AZN": "₼", "GEL2": "₾", "ETB": "Br", "TZS": "TSh",
    "UGX": "USh", "GHS": "₵", "ZMW": "ZK", "BWP": "P", "MUR": "₨",
    "MVR": "Rf", "LKR2": "Rs", "NPR": "₨", "AFN": "؋", "IRR": "﷼",
    "IQD": "IQD", "JOD": "JD", "KWD": "KD", "BHD": "BD", "OMR": "OMR",
    "QAR": "QR", "LBP": "LB", "SYP": "£", "YER": "﷼", "KGS2": "с",
}

#: E.164 country calling codes the source dataset cannot express.
#:
#: ``idd`` stores a shared trunk root (``+7``, ``+1``, ``+3``...) plus *national*
#: prefixes, so a few countries cannot be derived mechanically. These are the
#: assigned country codes for them, plus the territories the dataset leaves empty.
CALLING_OVERRIDES: dict[str, str] = {
    "RUS": "+7",
    "KAZ": "+7",
    "XKX": "+383",
    "ATA": "+672",
    "ALA": "+358",
    "VAT": "+379",
    "SGS": "+500",
    "ESH": "+212",
    "BES": "+599",
    "CUW": "+599",
    "MAF": "+590",
    "BLM": "+590",
    "GUF": "+594",
    "GLP": "+590",
    "MTQ": "+596",
    "AIA": "+1",
    "BMU": "+1",
    "CYM": "+1",
    "FMS": "+1",
    "GRL": "+299",
    "MSR": "+1",
    "NCL": "+687",
    "PRI": "+1",
    "SHN": "+290",
    "TCA": "+1",
    "VGB": "+1",
    "WLF": "+681",
    "SPM": "+508",
    "MYT": "+262",
    "REU": "+262",
    "ABW": "+297",
    "AND": "+376",
    "FLK": "+500",
    "PCN": "+64",
    "GIB": "+350",
    "IMN": "+44",
    "JEY": "+44",
    "GGY": "+44",
    "HMD": "+672",
    # North American Numbering Plan: the area code is *not* part of the country
    # code, so the dataset's first suffix must not be appended.
    "USA": "+1",
    "CAN": "+1",
    "SJM": "+47",
    "GRL2": "+299",
}

HEADER = '''"""ISO 3166-1 country and territory reference data.

Generated by ``scripts/gen_iso_table.py`` from the public ISO 3166-1 dataset and
checked in, so the game never depends on a network call or a third-party package
to know what countries exist.

Only *reference* data lives here: the ISO identifiers, display names in both game
languages, the continent grouping, the calling code and the currency. Nothing in
this module decides gameplay - :mod:`app.game.countries` turns these rows into
playable :class:`~app.game.countries.CountryDef` entries, and the database owns the
resulting catalogue.

Format note: the number formats in :mod:`app.game.sim_cards` are a documented
*synthetic game* representation inspired by how each country's numbers are grouped.
They make no claim about real numbering plans and no number produced here can
belong to a real subscriber.
"""

from __future__ import annotations

from dataclasses import dataclass

#: Continent grouping used by albums, events and the WORLD screen.
REGION_GROUPS: tuple[str, ...] = (
    "EUROPE",
    "AMERICAS",
    "ASIA",
    "MIDEAST",
    "AFRICA",
    "OCEANIA",
    "ANTARCTIC",
    "CIS",
)


@dataclass(frozen=True, slots=True)
class IsoCountry:
    """One ISO 3166-1 entry."""

    alpha2: str
    alpha3: str
    name_en: str
    name_ru: str
    region_group: str
    calling_code: str
    currency_code: str
    currency_symbol: str
    un_member: bool
    landlocked: bool

    @property
    def flag(self) -> str:
        """Regional-indicator emoji for the entry."""
        return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in self.alpha2)

    @property
    def numeric(self) -> str:
        return _NUMERIC_BY_ALPHA3.get(self.alpha3, "??")


def flag_from_alpha2(alpha2: str) -> str:
    """Emoji flag for a two-letter code; empty for anything unusable."""
    code = (alpha2 or "").strip().upper()
    if len(code) != 2 or not code.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in code)

'''


def main() -> int:
    source = Path(sys.argv[1] if len(sys.argv) > 1 else "countries.json")
    data = json.loads(source.read_text(encoding="utf-8"))

    rows: list[dict[str, object]] = []
    numeric: dict[str, str] = {}
    for entry in data:
        alpha2 = str(entry.get("cca2") or "").upper()
        alpha3 = str(entry.get("cca3") or "").upper()
        if len(alpha2) != 2 or len(alpha3) != 3:
            continue
        ccn3 = str(entry.get("ccn3") or "").zfill(3)
        if ccn3.isdigit():
            numeric[alpha3] = ccn3

        rus = (entry.get("translations") or {}).get("rus") or ""
        if isinstance(rus, dict):
            rus = rus.get("common") or rus.get("official") or ""
        ru = str(rus)
        en = str((entry.get("name") or {}).get("common") or alpha3)
        # A few territories have no Russian translation in the source dataset;
        # English is a better fallback than an empty string in a localised list.
        name_ru = ru or en

        region = REGION_MAP.get(str(entry.get("region") or ""), "EUROPE")
        if str(entry.get("subregion") or "") in SUBREGION_MAP:
            region = SUBREGION_MAP[str(entry["subregion"])]
        region = REGION_OVERRIDES.get(alpha3, region)

        idd = entry.get("idd") or {}
        calling = str(idd.get("root") or "")
        suffixes = [str(s) for s in (idd.get("suffixes") or []) if str(s)]
        if len(calling) == 2 and suffixes:
            # ``+4`` + ``9`` -> ``+49``. Countries that share a single-digit root
            # (``+7``, ``+1``) are excluded below because their suffixes are
            # national prefixes / area codes, not part of the country code.
            calling = calling + suffixes[0]
        calling = CALLING_OVERRIDES.get(alpha3, calling)

        currencies = entry.get("currencies") or {}
        currency_code = "USD"
        symbol = "$"
        if currencies:
            first_key = sorted(currencies)[0]
            currency_code = str(first_key).upper()
            raw_symbol = str(currencies[first_key].get("symbol") or "")
            symbol = (
                raw_symbol
                if currency_code not in SYMBOL_BLACKLIST and all(ch in ALLOWED_SYMBOLS for ch in raw_symbol)
                else currency_code
            )

        rows.append(
            {
                "alpha2": alpha2,
                "alpha3": alpha3,
                "name_en": en,
                "name_ru": name_ru,
                "region_group": region,
                "calling_code": calling,
                "currency_code": currency_code,
                "currency_symbol": symbol,
                "un_member": bool(entry.get("unMember")),
                "landlocked": bool(entry.get("landlocked")),
                "numeric": ccn3,
            }
        )

    rows.sort(key=lambda r: str(r["alpha3"]))

    out = [HEADER]
    out.append("ISO_COUNTRIES: tuple[IsoCountry, ...] = (\n")
    for row in rows:
        out.append(
            "    IsoCountry(\n"
            f"        alpha2={row['alpha2']!r},\n"
            f"        alpha3={row['alpha3']!r},\n"
            f"        name_en={row['name_en']!r},\n"
            f"        name_ru={row['name_ru']!r},\n"
            f"        region_group={row['region_group']!r},\n"
            f"        calling_code={row['calling_code']!r},\n"
            f"        currency_code={row['currency_code']!r},\n"
            f"        currency_symbol={row['currency_symbol']!r},\n"
            f"        un_member={row['un_member']!r},\n"
            f"        landlocked={row['landlocked']!r},\n"
            "    ),\n"
        )
    out.append(")\n\n")

    out.append("_NUMERIC_BY_ALPHA3: dict[str, str] = {\n")
    for row in rows:
        out.append(f"    {row['alpha3']!r}: {row['numeric']!r},\n")
    out.append("}\n\n")

    out.append(
        "ISO_BY_ALPHA2: dict[str, IsoCountry] = {country.alpha2: country for country in ISO_COUNTRIES}\n"
        "ISO_BY_ALPHA3: dict[str, IsoCountry] = {country.alpha3: country for country in ISO_COUNTRIES}\n"
        "\n"
        "\n"
        "def iso_country(code: str | None) -> IsoCountry | None:\n"
        '    """Resolve a 2- or 3-letter identifier (either ISO form)."""\n'
        "    if not code:\n"
        "        return None\n"
        "    text = str(code).strip().upper()\n"
        "    return ISO_BY_ALPHA3.get(text) or ISO_BY_ALPHA2.get(text)\n"
        "\n"
        "\n"
        "def is_known_country(code: str | None) -> bool:\n"
        "    return iso_country(code) is not None\n"
        "\n"
        "\n"
        "__all__ = [\n"
        '    "ISO_BY_ALPHA2",\n'
        '    "ISO_BY_ALPHA3",\n'
        '    "ISO_COUNTRIES",\n'
        '    "REGION_GROUPS",\n'
        '    "IsoCountry",\n'
        '    "flag_from_alpha2",\n'
        '    "is_known_country",\n'
        '    "iso_country",\n'
        "]\n"
    )

    target = Path(__file__).resolve().parents[1] / "app" / "game" / "iso_countries.py"
    target.write_text("".join(out), encoding="utf-8")
    print(f"wrote {target} with {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
