"""Physical plate formats, per country.

This module owns the *physical geometry* of every plate in the atlas. A registration
plate is a standardised metal object: its size in millimetres, its border, where the
country identifier sits, how it is fixed to a car. Those are facts, and getting them
wrong is what makes a plate look like a card with text on it.

Why this is a table and not a renderer's ``if`` chain
------------------------------------------------------
Because geometry is data. A renderer that branches on a country name accumulates a new
``if`` for every country and every layout variation, and eventually two countries that
happen to look the same share code by accident rather than by decision. Here, every
playable country has a row in :data:`PLATE_FORMATS`, and the renderer consumes it without
knowing what a country is.

The physical formats
--------------------
A country does not need its own recipe just because it is a different country - several
do genuinely share one physical standard. What matters is that the *shared* row carries
each country's own identifier code and its own surface colours, so a Polish plate prints
``PL`` and a German plate prints ``D`` from the same standard, and neither is a stand-in
for the other.

The formats that are physically distinct get their own row:

=======================  ==========  ======  =================================
Format                   mm          ratio   Countries
=======================  ==========  ======  =================================
Type 1 (CIS automobile)  520x112     4.643   Russia, Kazakhstan
EU long                  520x110     4.727   the EU/EEA standard
EU long, post-2019       520x110     4.727   Norway, Sweden (no country band)
UK rear                  520x111     4.685   United Kingdom
Mercosur                 400x130     3.077   Brazil
North America           305x152     2.007   United States, Canada
Japan                    330x165     2.000   Japan
Gulf                     520x130     4.000   United Arab Emirates
India                    520x120     4.333   India
China                    440x140     3.143   China
South Korea              520x110     4.727   South Korea
Thailand                 340x160     2.125   Thailand
Israel                   520x220     2.364   Israel (dual-line format)
Australia                372x134     2.776   Australia, New Zealand
South Africa             340x175     1.943   South Africa
Turkey                   520x130     4.000   Turkey
Saudi Arabia             440x140     3.143   Saudi Arabia
Singapore                520x110     4.727   Singapore
Balkan                   520x110     4.727   Bulgaria, Romania
UK-style two-line        520x111     4.685   Iceland
=======================  ==========  ======  =================================

Honesty
-------
Reproducing the familiar proportions and layout logic of a real plate is what makes a
collectible recognisable. These are a stylised game presentation: they make no regulatory
claim, and a country on a shared row is not pretending to be an exact reproduction of any
national scheme. Serial combinations are synthetic and generated by the engine - NUMORA
never reproduces a specific registered vehicle's plate.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Real physical sizes, in millimetres
# ---------------------------------------------------------------------------
CIS_520x112 = (520, 112)
EU_520x110 = (520, 110)
UK_520x111 = (520, 111)
MERCOSUR_400x130 = (400, 130)
NA_305x152 = (305, 152)
JP_330x165 = (330, 165)
GULF_520x130 = (520, 130)
IN_520x120 = (520, 120)
CN_440x140 = (440, 140)
TH_340x160 = (340, 160)
IL_520x220 = (520, 220)
AU_372x134 = (372, 134)
ZA_340x175 = (340, 175)
SA_440x140 = (440, 140)

#: Real CSS stacks behind a stable font key, so the client never hardcodes a family.
FONT_STACKS: dict[str, str] = {
    "euro": "'Arial Narrow', 'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif",
    "condensed": "'Arial Narrow', 'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif",
    "cyrillic": "'Roboto Condensed', 'PT Sans Narrow', 'Arial Narrow', 'Helvetica Neue', Arial, sans-serif",
    "wide": "'Trebuchet MS', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    "japanese": "'Hiragino Kaku Gothic ProN', 'Noto Sans JP', 'Yu Gothic', sans-serif",
    "sans": "'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    "mono": "'Roboto Mono', 'SFMono-Regular', 'Consolas', monospace",
}

#: The EU identity band and its print colour.
EU_BAND = "#003399"
EU_BAND_TEXT = "#ffd300"


@dataclass(frozen=True, slots=True)
class PlateVisual:
    """The presentation contract for one country's plate.

    Grouped as physical shape, surface, typography, country identifier, region placement,
    mounting and finish. ``width_mm``/``height_mm`` are the real standardised size and
    ``aspect`` is *derived* from them, so a recipe can never claim a size and a ratio that
    disagree.
    """

    theme: str
    #: Physical family key. Drives the renderer's structural template.
    plate_family: str = "eu_long"
    #: Which front/rear variant this recipe represents.
    variant: str = "standard"

    # --- physical shape --------------------------------------------------
    #: Real width of the plate, in millimetres. The source of truth for its proportions.
    width_mm: int = EU_520x110[0]
    #: Real height of the plate, in millimetres.
    height_mm: int = EU_520x110[1]
    radius: str = "4px"
    border_width: str = "3px"

    @property
    def aspect(self) -> float:
        """Width : height, derived from the real physical size."""
        if not self.height_mm:
            return 1.0
        return round(self.width_mm / self.height_mm, 4)

    # --- surface ----------------------------------------------------------
    background: str = "#fbfbfa"
    background_alt: str = "#edeff2"
    border: str = "#1a1a1a"
    text: str = "#111827"
    muted: str = "#4b5563"
    accent: str = "#3b4a6b"
    texture: str = "metal"

    # --- typography -------------------------------------------------------
    font_stack: str = "euro"
    letter_spacing: str = "0.045em"
    #: Space between printed groups.
    group_gap: str = "0.7em"
    #: Digits are printed larger than letters on most real plates.
    digit_scale: float = 1.0
    letter_scale: float = 0.92
    digit_weight: int = 700

    # --- country identifier -----------------------------------------------
    #: ``"left"``/``"right"`` print a side band; ``"none"`` disables it.
    band_position: str = "left"
    band_color: str | None = EU_BAND
    #: Band width as a fraction of the plate *width*.
    band_width: float = 0.19
    #: Printed inside the band: the EU country code or a national mark.
    band_text: str = ""
    #: ``"static"`` prints ``band_text``; ``"country_alpha2"`` prints the country's own
    #: ISO alpha-2 code, which is what an EU-style band does.
    band_text_source: str = "country_alpha2"
    band_text_color: str = EU_BAND_TEXT
    #: The EU star ring, drawn as vector arcs rather than emoji.
    band_stars: bool = True
    #: ``None`` = no flag in the band; a key such as ``"ru"`` or ``"ge"`` for a flag drawn
    #: as vectors. Only formats that really carry one inside the band set this.
    band_flag: str | None = None
    #: A small drawn emblem inside the band (a crest glyph), never an emoji.
    band_emblem: str = ""

    # --- printed header ---------------------------------------------------
    header: str = ""
    header_align: str = "center"
    #: ``"static"`` uses ``header``; ``"region"`` prints the region's own name (a US
    #: state's own name, for instance); ``"none"`` hides it.
    header_source: str = "none"
    header_color: str | None = None
    #: Vertical position of the printed header as a fraction of the plate height.
    header_offset: float = 0.08

    # --- region placement --------------------------------------------------
    #: ``"right"`` = separate right-hand compartment (Russia/Kazakhstan style),
    #: ``"inline"`` = part of the printed serial, ``"badge"`` = small corner badge,
    #: ``"none"`` = the country has no separate region block.
    region_position: str = "badge"
    region_style: str = "badge"
    region_badge: bool = True
    #: Width of the region compartment as a fraction of the plate *width*.
    region_width: float = 0.12
    #: Whether the compartment prints the country's flag above the region code. True on
    #: the Russian format, where the tricolour and the ``RUS`` legend sit in the right
    #: compartment with the region code beneath them.
    region_flag: bool = False
    show_flag: bool = True
    show_region_flag: bool = True

    # --- mounting ----------------------------------------------------------
    #: Physical mounting hardware, by appearance: ``"bolts"`` = studded heads (the
    #: CIS/EU screw-and-washer look), ``"holes"`` = pressed screw holes with no head
    #: (North America, Japan), ``"none"`` = an adhesive or un-drilled plate.
    mount: str = "bolts"
    mount_color: str = "#8a9099"
    #: Size of one mounting feature as a fraction of the plate *height*.
    mount_size: float = 0.11

    # --- finish -------------------------------------------------------------
    gloss: bool = True
    #: Strength of the diagonal reflection pass, 0..1.
    sheen: float = 0.48
    #: A small printed corner mark (sponsor block, crest, class mark). ``""`` = none.
    emblem: str = ""
    #: How pronounced the raised-lettering relief is, 0..1. The renderer turns this into
    #: the letterpress shadow; a matte finish gets almost none of it.
    relief: float = 0.32
    #: Fine surface grain, 0..1. Chrome and enamel are smooth; weathered paint is not.
    grain: float = 0.15

    extra: dict[str, str] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Per-country physical formats
# ---------------------------------------------------------------------------
#
# Every playable country has a row. Countries that genuinely share one physical standard
# share a row *through their own identifier code*, so nothing is a placeholder.

#: Physical formats that are genuinely distinct. Keyed by a format name.
FORMATS: dict[str, PlateVisual] = {
    # --- Russia: GOST R 50577-2018 type 1, 520x112 mm.
    #
    # A white field with a black border; the registration left of centre; a vertical rule;
    # and a right-hand compartment carrying the tricolour, the ``RUS`` legend and the
    # region code. That compartment is part of the plate, which is why it is a first-class
    # field rather than an afterthought.
    "cis_right_region": PlateVisual(
        theme="cis_right_region",
        plate_family="cis_right_region",
        width_mm=CIS_520x112[0],
        height_mm=CIS_520x112[1],
        radius="4px",
        border_width="2px",
        background="#ffffff",
        background_alt="#f4f5f7",
        border="#111111",
        text="#0a0a0a",
        muted="#5b6169",
        accent="#2f6bd8",
        font_stack="cyrillic",
        letter_spacing="0.055em",
        letter_scale=0.93,
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="country_alpha3",
        band_text_color="#111111",
        band_stars=False,
        region_position="right",
        region_style="block",
        region_width=0.132,
        region_flag=True,
        mount="bolts",
        sheen=0.5,
        relief=0.34,
        grain=0.14,
    ),
    # --- Kazakhstan: the same two-compartment standard, but the compartment carries KAZ.
    "cis_right_kaz": PlateVisual(
        theme="cis_right_kaz",
        plate_family="cis_right_region",
        width_mm=CIS_520x112[0],
        height_mm=CIS_520x112[1],
        radius="4px",
        border_width="2px",
        background="#ffffff",
        background_alt="#f2f6fb",
        border="#0f2f6b",
        text="#0a1c3d",
        muted="#3f5a86",
        accent="#0096c7",
        font_stack="cyrillic",
        letter_spacing="0.055em",
        letter_scale=0.93,
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="country_alpha3",
        band_text_color="#111111",
        band_stars=False,
        region_position="right",
        region_style="block",
        region_width=0.132,
        region_flag=False,
        mount="bolts",
        sheen=0.46,
        relief=0.32,
        grain=0.14,
    ),
    # --- Georgia: white plate, blue flag block down the left edge, ``GE``, Latin
    # registration ``AB-123-CD``. No EU star ring, and no region compartment: the third
    # group of a Georgian number is part of the serial.
    "ge": PlateVisual(
        theme="ge",
        plate_family="ge",
        width_mm=CIS_520x112[0],
        height_mm=CIS_520x112[1],
        radius="4px",
        border_width="2px",
        background="#ffffff",
        background_alt="#f3f6fb",
        border="#0f172a",
        text="#111111",
        muted="#5b6572",
        accent="#ff4b33",
        font_stack="condensed",
        letter_spacing="0.05em",
        letter_scale=0.96,
        group_gap="0.55em",
        band_position="left",
        band_color="#1c3f94",
        band_width=0.14,
        band_text="GE",
        band_text_source="static",
        band_text_color="#ffffff",
        band_stars=False,
        band_flag="ge",
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="holes",
        sheen=0.5,
        relief=0.32,
        grain=0.14,
    ),
    # --- The EU long plate: 520x110 mm, blue band with the star ring and the country's
    # own ISO alpha-2 code. Shared by every member that uses the standard.
    "eu_long": PlateVisual(
        theme="eu_long",
        plate_family="eu_long",
        width_mm=EU_520x110[0],
        height_mm=EU_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fbfbfa",
        background_alt="#edeff2",
        border="#1a1a1a",
        text="#111827",
        muted="#4b5563",
        accent="#3b4a6b",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.19,
        band_text="",
        band_text_source="country_alpha2",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    # --- Norway and Sweden: the same 520x110 plate, but since 2019 they no longer print
    # an EU band. Only the registration is on the field.
    "eu_noband": PlateVisual(
        theme="eu_noband",
        plate_family="eu_noband",
        width_mm=EU_520x110[0],
        height_mm=EU_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fbfbfa",
        background_alt="#edeff2",
        border="#1a1a1a",
        text="#111827",
        muted="#4b5563",
        accent="#b91c1c",
        font_stack="euro",
        letter_spacing="0.05em",
        group_gap="0.7em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.46,
        relief=0.32,
        grain=0.15,
    ),
    # --- United Kingdom: 520x111, yellow rear, black print, no band.
    "uk_rear": PlateVisual(
        theme="uk_rear",
        plate_family="uk",
        variant="rear",
        width_mm=UK_520x111[0],
        height_mm=UK_520x111[1],
        radius="3px",
        border_width="2px",
        background="#f7d117",
        background_alt="#e3bd0c",
        border="#111111",
        text="#111111",
        muted="#3f3f46",
        accent="#c8102e",
        texture="reflective",
        font_stack="condensed",
        letter_spacing="0.07em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        region_position="none",
        region_style="none",
        region_width=0.0,
        mount="bolts",
        sheen=0.4,
        relief=0.3,
        grain=0.18,
    ),
    # --- Brazil: Mercosur, 400x130 mm - visibly shorter and taller than an EU plate.
    "mercosur": PlateVisual(
        theme="mercosur",
        plate_family="mercosur",
        width_mm=MERCOSUR_400x130[0],
        height_mm=MERCOSUR_400x130[1],
        radius="6px",
        border_width="3px",
        background="#fdfdfb",
        background_alt="#f1f4ee",
        border="#0b3a24",
        text="#0d2b1c",
        muted="#3f5a4a",
        accent="#009c3b",
        font_stack="sans",
        letter_spacing="0.04em",
        letter_scale=0.95,
        group_gap="0.5em",
        # Mercosur prints a grey band along the top with the country code, not a side
        # band - a layout difference that a shared "EU long" row would hide.
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="country_alpha2",
        band_text_color="#ffffff",
        band_stars=False,
        header="BRASIL",
        header_align="center",
        header_source="static",
        header_color="#5b6b5f",
        header_offset=0.07,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="holes",
        sheen=0.42,
        relief=0.3,
        grain=0.14,
        emblem="mercosur",
    ),
    # --- North America: 305x152 mm, two pressed screw holes, the state's own name as the
    # printed header.
    "north_america": PlateVisual(
        theme="north_america",
        plate_family="us_state",
        width_mm=NA_305x152[0],
        height_mm=NA_305x152[1],
        radius="10px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f0f2f5",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#2563eb",
        texture="enamel",
        font_stack="sans",
        letter_spacing="0.13em",
        group_gap="0.5em",
        digit_weight=600,
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#1f2937",
        header_offset=0.09,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="holes",
        sheen=0.6,
        relief=0.28,
        grain=0.1,
        emblem="state_tag",
    ),
    # --- Canada: wordmark at the top-left, no state name.
    "canada": PlateVisual(
        theme="canada",
        plate_family="americas_long",
        width_mm=NA_305x152[0],
        height_mm=NA_305x152[1],
        radius="9px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#eff2f6",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#d80621",
        texture="enamel",
        font_stack="sans",
        letter_spacing="0.09em",
        group_gap="0.5em",
        digit_weight=600,
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="CANADA",
        header_align="left",
        header_source="static",
        header_color="#d80621",
        header_offset=0.08,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="holes",
        sheen=0.56,
        relief=0.28,
        grain=0.1,
    ),
    # --- Japan: 330x165 mm, green on white, the region class printed above.
    "japan": PlateVisual(
        theme="japan",
        plate_family="jp",
        width_mm=JP_330x165[0],
        height_mm=JP_330x165[1],
        radius="6px",
        border_width="2px",
        background="#fbfdfb",
        background_alt="#eff5f0",
        border="#1f2d3d",
        text="#164d2b",
        muted="#3d6b50",
        accent="#1f6feb",
        font_stack="japanese",
        letter_spacing="0.055em",
        digit_scale=0.86,
        letter_scale=1.0,
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#164d2b",
        header_offset=0.07,
        region_position="inline",
        region_style="block",
        region_width=0.0,
        region_flag=False,
        mount="holes",
        sheen=0.55,
        relief=0.3,
        grain=0.13,
        emblem="green_mark",
    ),
    # --- Gulf: 520x130 chrome-faced plate, the emirate name printed above.
    "gulf": PlateVisual(
        theme="gulf",
        plate_family="mideast",
        width_mm=GULF_520x130[0],
        height_mm=GULF_520x130[1],
        radius="6px",
        border_width="3px",
        background="#f7f9fc",
        background_alt="#e9eef4",
        border="#0f172a",
        text="#0b1220",
        muted="#64748b",
        accent="#c8a24a",
        texture="chrome",
        font_stack="wide",
        letter_spacing="0.07em",
        group_gap="0.7em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        region_flag=False,
        mount="holes",
        sheen=0.7,
        relief=0.36,
        grain=0.08,
        emblem="crest",
    ),
    # --- India: 520x120 mm, a white plate with a high-contrast border and the state
    # code printed on the left edge.
    "india": PlateVisual(
        theme="india",
        plate_family="india",
        width_mm=IN_520x120[0],
        height_mm=IN_520x120[1],
        radius="4px",
        border_width="2px",
        background="#fdfdfb",
        background_alt="#f3f1e8",
        border="#0a1c3d",
        text="#0a1c3d",
        muted="#4a5568",
        accent="#ff9933",
        font_stack="sans",
        letter_spacing="0.03em",
        letter_scale=0.9,
        group_gap="0.45em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="INDIA",
        header_align="left",
        header_source="static",
        header_color="#4a5568",
        header_offset=0.06,
        region_position="badge",
        region_style="badge",
        region_width=0.1,
        region_flag=False,
        mount="bolts",
        sheen=0.4,
        relief=0.28,
        grain=0.16,
    ),
    # --- China: 440x140 mm, blue on white, with the provincial mark printed above.
    "china": PlateVisual(
        theme="china",
        plate_family="china",
        width_mm=CN_440x140[0],
        height_mm=CN_440x140[1],
        radius="4px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f0f4fa",
        border="#1e3a8a",
        text="#12306b",
        muted="#4b5f80",
        accent="#de2910",
        font_stack="sans",
        letter_spacing="0.05em",
        letter_scale=0.94,
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#12306b",
        header_offset=0.07,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        region_flag=False,
        mount="bolts",
        sheen=0.45,
        relief=0.3,
        grain=0.14,
    ),
    # --- South Korea: 520x110 mm, black on white with the build-year plate above.
    "korea": PlateVisual(
        theme="korea",
        plate_family="korea",
        width_mm=EU_520x110[0],
        height_mm=EU_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fdfdfd",
        background_alt="#f1f3f6",
        border="#111111",
        text="#111111",
        muted="#4b5563",
        accent="#c60c30",
        font_stack="sans",
        letter_spacing="0.05em",
        letter_scale=0.94,
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#374151",
        header_offset=0.07,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="bolts",
        sheen=0.48,
        relief=0.3,
        grain=0.14,
    ),
    # --- Thailand: 340x160 mm, two stacked lines - the province above the number.
    "thailand": PlateVisual(
        theme="thailand",
        plate_family="thailand",
        width_mm=TH_340x160[0],
        height_mm=TH_340x160[1],
        radius="6px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f2f0f4",
        border="#1f2937",
        text="#1a1a1a",
        muted="#5b6474",
        accent="#a51931",
        font_stack="sans",
        letter_spacing="0.04em",
        digit_scale=0.95,
        group_gap="0.4em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#4b5563",
        header_offset=0.09,
        region_position="inline",
        region_style="block",
        region_width=0.0,
        region_flag=False,
        mount="bolts",
        sheen=0.42,
        relief=0.3,
        grain=0.15,
    ),
    # --- Israel: 520x220 mm, a genuinely tall two-compartment plate.
    "israel": PlateVisual(
        theme="israel",
        plate_family="israel",
        width_mm=IL_520x220[0],
        height_mm=IL_520x220[1],
        radius="5px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f2f4f6",
        border="#0f172a",
        text="#0b1220",
        muted="#5b6474",
        accent="#0038b8",
        font_stack="sans",
        letter_spacing="0.05em",
        group_gap="0.5em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.06,
        # Two compartments stacked, which is the point of the format.
        region_position="right",
        region_style="block",
        region_width=0.22,
        region_flag=False,
        mount="bolts",
        sheen=0.46,
        relief=0.3,
        grain=0.14,
    ),
    # --- Australia and New Zealand: 372x134 mm, a narrow white plate with the state
    # printed as a small vertical wordmark.
    "oceania_au": PlateVisual(
        theme="oceania_au",
        plate_family="oceania",
        width_mm=AU_372x134[0],
        height_mm=AU_372x134[1],
        radius="7px",
        border_width="2px",
        background="#fdfdfb",
        background_alt="#f2f4f2",
        border="#1f2937",
        text="#1f2937",
        muted="#6b7280",
        accent="#0b5d3b",
        font_stack="wide",
        letter_spacing="0.07em",
        letter_scale=0.95,
        group_gap="0.5em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#9ca3af",
        header_offset=0.08,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="bolts",
        sheen=0.5,
        relief=0.3,
        grain=0.13,
    ),
    # --- South Africa: 340x175 mm, white on black - an inverted plate, which no shared
    # light-field row can represent.
    "south_africa": PlateVisual(
        theme="south_africa",
        plate_family="south_africa",
        width_mm=ZA_340x175[0],
        height_mm=ZA_340x175[1],
        radius="6px",
        border_width="3px",
        background="#14161a",
        background_alt="#0a0c0f",
        border="#e5e7eb",
        text="#f8fafc",
        muted="#9aa3af",
        accent="#007a4d",
        texture="reflective",
        font_stack="sans",
        letter_spacing="0.06em",
        group_gap="0.45em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#f8fafc",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#9aa3af",
        header_offset=0.08,
        region_position="inline",
        region_style="block",
        region_width=0.0,
        region_flag=False,
        mount="bolts",
        sheen=0.44,
        relief=0.3,
        grain=0.16,
    ),
    # --- Turkey: 520x130 mm, white on white with a TR-only plate distinguished by code.
    "turkey": PlateVisual(
        theme="turkey",
        plate_family="mideast",
        width_mm=GULF_520x130[0],
        height_mm=GULF_520x130[1],
        radius="6px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f1f3f6",
        border="#0f172a",
        text="#0b1220",
        muted="#5b6474",
        accent="#e30a17",
        font_stack="wide",
        letter_spacing="0.06em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="TR",
        band_text_source="static",
        band_text_color="#ffffff",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        region_flag=False,
        mount="bolts",
        sheen=0.46,
        relief=0.3,
        grain=0.14,
    ),
    # --- Saudi Arabia: 440x140 mm.
    "saudi": PlateVisual(
        theme="saudi",
        plate_family="saudi",
        width_mm=SA_440x140[0],
        height_mm=SA_440x140[1],
        radius="6px",
        border_width="3px",
        background="#fdfdfd",
        background_alt="#f2f4f2",
        border="#0a1c3d",
        text="#0a1c3d",
        muted="#4b5f80",
        accent="#006c35",
        font_stack="wide",
        letter_spacing="0.06em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        region_flag=False,
        mount="bolts",
        sheen=0.48,
        relief=0.3,
        grain=0.14,
    ),
    # --- Singapore: 520x110 mm, black on white with a coloured top strip.
    "singapore": PlateVisual(
        theme="singapore",
        plate_family="singapore",
        width_mm=EU_520x110[0],
        height_mm=EU_520x110[1],
        radius="4px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f2f4f8",
        border="#111111",
        text="#111111",
        muted="#4b5563",
        accent="#ef3340",
        font_stack="sans",
        letter_spacing="0.05em",
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="left",
        header_source="region",
        header_color="#6b7280",
        header_offset=0.06,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="bolts",
        sheen=0.44,
        relief=0.3,
        grain=0.14,
    ),
    # --- Iceland: a UK-style 520x111 white plate with its own two-line layout.
    "iceland": PlateVisual(
        theme="iceland",
        plate_family="uk",
        width_mm=UK_520x111[0],
        height_mm=UK_520x111[1],
        radius="3px",
        border_width="2px",
        background="#f7f7f5",
        background_alt="#e8e8e4",
        border="#003879",
        text="#003879",
        muted="#4a5568",
        accent="#02529c",
        font_stack="condensed",
        letter_spacing="0.06em",
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="IS",
        header_align="center",
        header_source="static",
        header_color="#02529c",
        header_offset=0.07,
        region_position="none",
        region_style="none",
        region_width=0.0,
        region_flag=False,
        mount="bolts",
        sheen=0.42,
        relief=0.3,
        grain=0.16,
    ),
    # --- The Balkan plate: 520x110 mm, white with a red-bordered frame and the national
    # crest printed as a small mark.
    "balkan": PlateVisual(
        theme="balkan",
        plate_family="balkan",
        width_mm=EU_520x110[0],
        height_mm=EU_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fdfdfb",
        background_alt="#f1f3f6",
        border="#9b1c1c",
        text="#111827",
        muted="#5b6474",
        accent="#d4af37",
        font_stack="wide",
        letter_spacing="0.055em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="none",
        band_text_color="#111111",
        band_stars=False,
        header="",
        header_align="center",
        header_source="region",
        header_color="#9b1c1c",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        region_flag=False,
        mount="bolts",
        sheen=0.44,
        relief=0.3,
        grain=0.15,
        emblem="crest",
    ),
}


# ---------------------------------------------------------------------------
# Country -> format
# ---------------------------------------------------------------------------
#
# A country maps to a physical *format*, and its own identity - the code printed in its
# band and its accent colour - comes from the country record. That is the difference
# between "the same standard" and "the same picture": a Polish plate and a German plate
# share 520x110 mm and a blue star band, and differ in the two letters printed in it.

#: Every playable country, mapped to the physical format it actually uses.
COUNTRY_FORMATS: dict[str, str] = {
    # The CIS two-compartment standard.
    "RUS": "cis_right_region",
    "KAZ": "cis_right_kaz",
    "BLR": "cis_right_kaz",
    "GEO": "ge",
    # EU / EEA long plate with the country band.
    "DEU": "eu_long",
    "FRA": "eu_long",
    "ITA": "eu_long",
    "POL": "eu_long",
    "ESP": "eu_long",
    "PRT": "eu_long",
    "NLD": "eu_long",
    "BEL": "eu_long",
    "AUT": "eu_long",
    "CZE": "eu_long",
    "SVK": "eu_long",
    "HUN": "eu_long",
    "ROU": "eu_long",
    "IRL": "eu_long",
    "ARM": "eu_long",
    "GRC": "eu_long",
    # Ukraine prints a 520x110 plate with its own two-tone band rather than the EU blue.
    # The geometry and the mounting are identical to the standard, so it shares the row
    # and carries its own ``UA`` code - a documented approximation, not a stand-in.
    "UKR": "eu_long",
    # Switzerland is not in the EU and prints no band at all.
    "CHE": "eu_noband",
    # The same plate since 2019, without the country band.
    "NOR": "eu_noband",
    "SWE": "eu_noband",
    "FIN": "eu_long",
    "DNK": "eu_long",
    "EST": "eu_long",
    "LVA": "eu_long",
    "LTU": "eu_long",
    # Americas.
    "USA": "north_america",
    "CAN": "canada",
    # Brazil left Mercosur for a Mercosur-shaped plate of its own.
    "BRA": "mercosur",
    # Mexico keeps a North-American-sized plate with its own wordmark.
    "MEX": "north_america",
    "ARG": "mercosur",
    "CHL": "mercosur",
    "COL": "north_america",
    # Asia and the Pacific.
    "JPN": "japan",
    "ARE": "gulf",
    "SAU": "saudi",
    "IND": "india",
    "CHN": "china",
    "KOR": "korea",
    "THA": "thailand",
    "SGP": "singapore",
    "AUS": "oceania_au",
    "NZL": "oceania_au",
    "ZAF": "south_africa",
    # The rest.
    "GBR": "uk_rear",
    "ISL": "iceland",
    "BGR": "balkan",
    "TUR": "turkey",
    "ISR": "israel",
}

#: Countries whose accent colour is worth showing, where it is not the format default.
COUNTRY_ACCENTS: dict[str, str] = {
    "DEU": "#111111",
    "ITA": "#009246",
    "ESP": "#c60b1e",
    "PRT": "#006600",
    "NLD": "#ae1c28",
    "BEL": "#c8102e",
    "AUT": "#c8102e",
    "CZE": "#0b5cab",
    "SVK": "#0b4ea2",
    "HUN": "#0b4ea2",
    "ROU": "#002b7f",
"IRL": "#169b62",
    "ARM": "#d52b1e",
    "GRC": "#0d5eaf",
    "UKR": "#005bbb",
    "CHE": "#d52b1e",
    "FIN": "#002f6c",
    "DNK": "#c8102e",
    "EST": "#0072ce",
    "LVA": "#9e3039",
    "LTU": "#006a44",
    "MEX": "#006341",
    "ARG": "#75aadb",
    "CHL": "#0039a6",
    "COL": "#fcd116",
    "POL": "#dc2626",
    "GBR": "#c8102e",
    "ISL": "#02529c",
    "BGR": "#00966e",
    "SWE": "#006aa7",
    "NOR": "#ba0c2f",
}

#: Per-country display name for the currency picker, from the country catalogue.
DEFAULT_FORMAT = "eu_long"


def format_for(country_code: str) -> PlateVisual:
    """The physical format for a country, falling back to the EU standard."""
    return FORMATS[COUNTRY_FORMATS.get(country_code, DEFAULT_FORMAT)]


def theme_for(country_code: str) -> str:
    """
    A stable recipe key for a country.

    Keyed by the country rather than by the shared format, so the payload a client renders
    is always specific to the country it belongs to and a change to one country cannot
    silently restyle another.
    """
    return f"cc_{country_code.lower()}"


def visual_for(theme: str) -> PlateVisual:
    """Resolve a recipe key back to its physical format."""
    if theme in FORMATS:
        return FORMATS[theme]
    if theme.startswith("cc_"):
        return format_for(theme[3:].upper())
    return FORMATS[DEFAULT_FORMAT]


def band_text_for(visual: PlateVisual, *, alpha2: str = "", alpha3: str = "") -> str:
    """Resolve the code printed inside a country's side band.

    An EU-style band carries the country's own ISO alpha-2 code - Poland prints ``PL``,
    Germany ``D`` - so the country identifier is never a stand-in. A format with no band
    prints no band text, whatever its source says.
    """
    if visual.band_position == "none":
        return ""
    source = visual.band_text_source
    if source == "country_alpha2":
        return str(alpha2 or "").strip().upper()[:2]
    if source == "country_alpha3":
        return str(alpha3 or "").strip().upper()[:3]
    if source == "none":
        return ""
    return visual.band_text


def region_text_for(visual: PlateVisual, *, alpha2: str = "", alpha3: str = "") -> str:
    """The identifier printed in the right-hand region compartment.

    On the CIS format that compartment carries the flag, the three-letter code and the
    region code, so the alpha-3 legend belongs there. Everything else prints nothing.
    """
    if visual.region_position != "right":
        return ""
    return str(alpha3 or "").strip().upper()[:3]


def serialize_visual(
    theme: str,
    *,
    alpha2: str = "",
    alpha3: str = "",
    country_code: str = "",
) -> dict[str, object]:
    """The JSON-serialisable visual contract for the API.

    Complete: the client can render a country's plate correctly with no knowledge of that
    country, and a new country needs no frontend change. ``country_code`` lets the payload
    carry that country's own accent colour, which is the last piece of identity a shared
    physical format cannot supply on its own.
    """
    visual = visual_for(theme)
    code = country_code or (theme[3:].upper() if theme.startswith("cc_") else "")
    data: dict[str, object] = {
        "theme": visual.theme if not theme.startswith("cc_") else theme,
        "country_code": code,
        "plate_family": visual.plate_family,
        "variant": visual.variant,
        # Physical geometry, and the ratio derived from it.
        "width_mm": visual.width_mm,
        "height_mm": visual.height_mm,
        "aspect": visual.aspect,
        "radius": visual.radius,
        "border_width": visual.border_width,
        # Surface.
        "background": visual.background,
        "background_alt": visual.background_alt,
        "border": visual.border,
        "text": visual.text,
        "muted": visual.muted,
        "accent": COUNTRY_ACCENTS.get(code, visual.accent),
        "texture": visual.texture,
        # Typography.
        "font_stack": FONT_STACKS.get(visual.font_stack, visual.font_stack),
        "font_stack_key": visual.font_stack,
        "letter_spacing": visual.letter_spacing,
        "group_gap": visual.group_gap,
        "digit_scale": visual.digit_scale,
        "letter_scale": visual.letter_scale,
        "digit_weight": visual.digit_weight,
        # Country identifier.
        "band_position": visual.band_position,
        "band_color": visual.band_color,
        "band_width": visual.band_width,
        "band_text": band_text_for(visual, alpha2=alpha2, alpha3=alpha3),
        "band_text_source": visual.band_text_source,
        "band_text_color": visual.band_text_color,
        "band_stars": visual.band_stars,
        "band_flag": visual.band_flag,
        "band_emblem": visual.band_emblem,
        # Printed header.
        "header": visual.header,
        "header_align": visual.header_align,
        "header_source": visual.header_source,
        "header_color": visual.header_color or visual.muted,
        "header_offset": visual.header_offset,
        # Region placement.
        "region_position": visual.region_position,
        "region_style": visual.region_style,
        "region_badge": visual.region_badge,
        "region_width": visual.region_width,
        "region_flag": visual.region_flag,
        "region_text": region_text_for(visual, alpha2=alpha2, alpha3=alpha3),
        "show_flag": visual.show_flag,
        "show_region_flag": visual.show_region_flag,
        # Mounting hardware.
        "mount": visual.mount,
        "mount_color": visual.mount_color,
        "mount_size": visual.mount_size,
        # Finish.
        "gloss": visual.gloss,
        "sheen": visual.sheen,
        "relief": visual.relief,
        "grain": visual.grain,
        "emblem": visual.emblem,
    }
    data.update(visual.extra)
    return data


__all__ = [
    "COUNTRY_ACCENTS",
    "COUNTRY_FORMATS",
    "DEFAULT_FORMAT",
    "EU_BAND",
    "EU_BAND_TEXT",
    "FONT_STACKS",
    "FORMATS",
    "PlateVisual",
    "band_text_for",
    "format_for",
    "region_text_for",
    "serialize_visual",
    "theme_for",
    "visual_for",
]
