"""Country plate presentation recipes.

Every plate in NUMORA is rendered from a *recipe* the server sends with the
collectible. This module owns those recipes: proportions, surface, typography,
country identifier, region placement, mounting hardware and finish. The client
renders the recipe and never decides how a country's plate looks.

Physical reference
------------------
Every recipe declares the plate's **real physical size in millimetres** and derives its
aspect ratio from that, rather than carrying a hand-tuned number. This is the single most
important correctness property in the module: a registration plate's proportions are a
legal, standardised thing, and a plate rendered at the wrong ratio does not read as a
plate at all - it reads as a card with text on it.

======================  ========  ======  =============================
Format                  mm        ratio   Used by
======================  ========  ======  =============================
Type 1 (automobile)     520x112   4.643   Russia, Kazakhstan
EU long                 520x110   4.727   Germany, Poland, France, Italy
UK rear                 520x111   4.685   United Kingdom
US / Canada             305x152   2.007   North America
Japan                   330x165   2.000   Japan
UAE                     520x130   4.000   United Arab Emirates
======================  ========  ======  =============================

Design contract
---------------
* One recipe per physical plate family, with a **country-specific recipe** whenever a
  launch country has its own real layout.
* ``width_mm``/``height_mm`` are the source of truth; ``aspect`` is computed from them.
  A recipe cannot claim a size and a ratio that disagree.
* No giant flag emoji standing in for a plate identifier. The country identifier is a
  small printed code inside a proper side band - the EU blue band with the country's own
  alpha-2 code for EU-style plates - plus, for the formats that really carry one, a
  flag drawn as vectors rather than pasted over the object.
* Country-specific layout is expressed in data: physical size, letter/digit hierarchy,
  where the region block sits, what the mounting hardware looks like, how reflective the
  surface is and how pronounced the letter relief is.
* Every recipe degrades to a documented generic family, which is honestly labelled as a
  game layout rather than a reproduction of any real scheme.

Honesty
-------
Recipes reproduce the *familiar proportions and layout logic* of real plates so a
collectible is instantly recognisable. They are a stylised game presentation: they make
no regulatory claim, and a country shipped on a generic family is not pretending to be
an exact reproduction. Serial combinations are synthetic, generated by the engine -
NUMORA never reproduces a specific registered vehicle's plate.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Shared presentation constants
# ---------------------------------------------------------------------------

#: Real CSS stacks behind a stable font key, so the client never hardcodes a family.
FONT_STACKS: dict[str, str] = {
    "euro": "'Arial Narrow', 'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif",
    "condensed": "'Arial Narrow', 'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif",
    "cyrillic": "'Roboto Condensed', 'PT Sans Narrow', 'Arial Narrow', 'Helvetica Neue', Arial, sans-serif",
    "wide": "'Trebuchet MS', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    "japanese": "'Hiragino Kaku Gothic ProN', 'Noto Sans JP', 'Yu Gothic', sans-serif",
    "sans": "'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    "mono": "'Roboto Mono', 'SFMono-Regular', 'Consolas', monospace",
}

#: The EU band colour (EU identity blue) and its print colour.
EU_BAND = "#003399"
EU_BAND_TEXT = "#ffd300"

# ---------------------------------------------------------------------------
# Physical reference sizes, in millimetres
# ---------------------------------------------------------------------------
#: GOST R 50577-2018 type 1 - the automobile plate used across the CIS.
PLATE_520x112 = (520, 112)
#: The European long plate most EU member states use.
PLATE_520x110 = (520, 110)
#: North American standard issue plate.
PLATE_305x152 = (305, 152)
#: Japanese small-vehicle plate.
PLATE_330x165 = (330, 165)
#: Gulf-style plate, 520x130.
PLATE_520x130 = (520, 130)


@dataclass(frozen=True, slots=True)
class PlateVisual:
    """Presentation contract for one country's plate family.

    Everything here is configuration for the renderer, grouped as physical shape,
    surface, typography, country identifier, region placement, mounting and finish.

    ``width_mm``/``height_mm`` are the real standardised size of the format; ``aspect``
    is derived from them, so the declared size and the rendered ratio can never disagree.
    """

    theme: str
    #: Physical family key. Drives the renderer's structural template.
    plate_family: str = "eu_long"
    #: Which front/rear variant this recipe represents.
    variant: str = "standard"

    # --- physical shape --------------------------------------------------
    #: Real width of the plate, in millimetres. The source of truth for its proportions.
    width_mm: int = PLATE_520x112[0]
    #: Real height of the plate, in millimetres.
    height_mm: int = PLATE_520x112[1]
    radius: str = "6px"
    border_width: str = "2px"

    @property
    def aspect(self) -> float:
        """Width : height, derived from the real physical size."""
        if not self.height_mm:
            return 1.0
        return round(self.width_mm / self.height_mm, 4)

    # --- surface ----------------------------------------------------------
    background: str = "#f4f6fb"
    #: Second stop of the face gradient, giving the enamel a slight falloff.
    background_alt: str = "#e8ecf4"
    border: str = "#1f2937"
    text: str = "#111827"
    muted: str = "#6b7280"
    accent: str = "#7c5cff"
    texture: str = "metal"

    # --- typography -------------------------------------------------------
    font_stack: str = "euro"
    letter_spacing: str = "0.06em"
    #: Space between printed groups.
    group_gap: str = "0.9em"
    #: Digits are printed larger than letters on most real plates.
    digit_scale: float = 1.0
    letter_scale: float = 0.92
    digit_weight: int = 700

    # --- country identifier -----------------------------------------------
    #: ``"left"``/``"right"`` print a side band; ``"none"`` disables it.
    band_position: str = "left"
    band_color: str | None = None
    #: Band width as a fraction of the plate *width*.
    band_width: float = 0.0
    #: Printed inside the band: the EU country code or a national mark.
    band_text: str = ""
    #: ``"static"`` prints ``band_text``; ``"country_alpha2"``/``"country_alpha3"``
    #: print the country's own ISO code, which is what an EU-style band does.
    band_text_source: str = "static"
    band_text_color: str = "#ffffff"
    #: The EU star ring, drawn as vector arcs rather than emoji.
    band_stars: bool = False
    #: ``None`` = no flag in the band; ``"ru"`` = the Russian tricolour drawn as three
    #: CSS bands. Only formats that really carry one inside the band set this.
    band_flag: str | None = None
    #: A small drawn emblem inside the band (a crest glyph), never an emoji.
    band_emblem: str = ""

    # --- header ------------------------------------------------------------
    header: str = ""
    header_align: str = "center"
    #: ``"static"`` uses ``header``; ``"region"`` prints the region's name (a US
    #: state's own name, so no two states read the same); ``"none"`` hides it.
    header_source: str = "static"
    header_color: str | None = None
    #: Vertical position of the printed header as a fraction of the plate height.
    header_offset: float = 0.08

    # --- region placement ---------------------------------------------------
    #: ``"right"`` = separate right-hand compartment (Russia/Kazakhstan style),
    #: ``"inline"`` = part of the printed serial, ``"badge"`` = small corner badge,
    #: ``"none"`` = the country has no separate region block.
    region_position: str = "inline"
    region_style: str = "block"
    region_badge: bool = True
    #: Width of the region compartment as a fraction of the plate *width*. On a real
    #: two-compartment plate this is a printed measurement, not a preference.
    region_width: float = 0.0
    #: Whether the compartment prints the country's flag above the region code. True on
    #: the Russian format, where the tricolour and the ``RUS`` legend sit in the right
    #: compartment with the region code beneath them.
    region_flag: bool = False
    show_flag: bool = True
    show_region_flag: bool = True

    # --- mounting -----------------------------------------------------------
    #: Physical mounting hardware, by appearance: ``"bolts"`` = studded heads (the
    #: CIS/EU screw-and-washer look), ``"holes"`` = pressed screw holes with no head
    #: (North America, Japan), ``"none"`` = an adhesive or un-drilled plate.
    mount: str = "bolts"
    mount_color: str = "#8a9099"
    #: Size of one mounting feature as a fraction of the plate *height*.
    mount_size: float = 0.11

    # --- finish --------------------------------------------------------------
    gloss: bool = True
    #: Strength of the diagonal reflection pass, 0..1.
    sheen: float = 0.5
    #: A small printed corner mark (sponsor block, crest, class mark). ``""`` = none.
    emblem: str = ""
    #: How pronounced the raised-lettering relief is, 0..1. The renderer turns this into
    #: the letterpress shadow; a matte finish gets almost none of it.
    relief: float = 0.35
    #: Fine surface grain, 0..1. Chrome and enamel are smooth; weathered paint is not.
    grain: float = 0.16

    extra: dict[str, str] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Country-specific recipes for the launch set
# ---------------------------------------------------------------------------
PLATE_VISUALS: dict[str, PlateVisual] = {
    # --- Russia: GOST R 50577-2018 type 1, 520x112 mm (ratio 4.643).
    #
    # The real geometry: a white field with a black border; the registration
    # ``<letter><3 digits><2 letters>`` set left of centre; a vertical rule; and a
    # right-hand compartment carrying the tricolour, the ``RUS`` legend and - beneath
    # them - the region code. That compartment is *part of the plate*, not an
    # afterthought, which is why it is a first-class field here rather than a side band.
    "ru": PlateVisual(
        theme="ru",
        plate_family="cis_right_region",
        width_mm=PLATE_520x112[0],
        height_mm=PLATE_520x112[1],
        radius="4px",
        border_width="2px",
        background="#ffffff",
        background_alt="#f4f5f7",
        border="#111111",
        text="#0a0a0a",
        muted="#5b6169",
        accent="#2f6bd8",
        texture="metal",
        font_stack="cyrillic",
        letter_spacing="0.055em",
        letter_scale=0.93,
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="country_alpha3",
        band_text_color="#111111",
        header="",
        header_source="none",
        region_position="right",
        region_style="block",
        region_width=0.132,
        region_flag=True,
        mount="bolts",
        sheen=0.5,
        relief=0.34,
        grain=0.14,
        emblem="",
    ),
    # --- Kazakhstan: the same two-compartment geometry on the same 520x112 plate, but
    # the right compartment carries the KAZ code instead of a flag.
    "kz": PlateVisual(
        theme="kz",
        plate_family="cis_right_region",
        width_mm=PLATE_520x112[0],
        height_mm=PLATE_520x112[1],
        radius="4px",
        border_width="2px",
        background="#ffffff",
        background_alt="#f2f6fb",
        border="#0f2f6b",
        text="#0a1c3d",
        muted="#3f5a86",
        accent="#0096c7",
        texture="metal",
        font_stack="cyrillic",
        letter_spacing="0.055em",
        letter_scale=0.93,
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        band_text_source="country_alpha3",
        band_text_color="#111111",
        header="",
        header_source="none",
        region_position="right",
        region_style="block",
        region_width=0.132,
        region_flag=False,
        mount="bolts",
        sheen=0.46,
        relief=0.32,
        grain=0.14,
        emblem="",
    ),
    # --- Germany: 520x110 EU long plate, blue EU band with the D and the star ring,
    # and the district seal beside the registration.
    "de": PlateVisual(
        theme="de",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fdfdfb",
        background_alt="#eeefe9",
        border="#111111",
        text="#111111",
        muted="#3f3f46",
        accent="#111111",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.19,
        band_text="D",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="seal",
        region_width=0.12,
        mount="bolts",
        sheen=0.58,
        relief=0.32,
        grain=0.15,
    ),
    # --- Poland: EU band with PL and the star ring.
    "pol": PlateVisual(
        theme="pol",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fbfbf8",
        background_alt="#ebedef",
        border="#1a1a1a",
        text="#111827",
        muted="#4b5563",
        accent="#dc2626",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.19,
        band_text="PL",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.52,
        relief=0.32,
        grain=0.15,
    ),
    # --- France: EU band with F, department seal.
    "fr": PlateVisual(
        theme="fr",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#ffffff",
        background_alt="#f2f3f6",
        border="#1f2937",
        text="#0b1220",
        muted="#5b6474",
        accent="#0055a4",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.2,
        band_text="F",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="seal",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    # --- Italy: EU band with I, province code beside the registration.
    "it": PlateVisual(
        theme="it",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#ffffff",
        background_alt="#f2f5f2",
        border="#1f2937",
        text="#0b1220",
        muted="#5b6474",
        accent="#009246",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.2,
        band_text="I",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="block",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    # --- United Kingdom: 520x111 yellow rear plate, black print, no EU band.
    "gb": PlateVisual(
        theme="gb",
        plate_family="uk",
        variant="rear",
        width_mm=520,
        height_mm=111,
        radius="3px",
        border_width="2px",
        background="#f7d117",
        background_alt="#e3bd0c",
        border="#111111",
        text="#111111",
        muted="#3f3f46",
        accent="#c8102e",
        texture="reflective",
        font_stack="condensed",
        letter_spacing="0.07em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_source="none",
        region_position="none",
        region_style="none",
        region_width=0.0,
        mount="bolts",
        sheen=0.4,
        relief=0.3,
        grain=0.18,
    ),
    # --- Japan: 330x165 plate, green on white, small class digit, region name up top.
    "jp": PlateVisual(
        theme="jp",
        plate_family="jp",
        width_mm=PLATE_330x165[0],
        height_mm=PLATE_330x165[1],
        radius="6px",
        border_width="2px",
        background="#fbfdfb",
        background_alt="#eff5f0",
        border="#1f2d3d",
        text="#164d2b",
        muted="#3d6b50",
        accent="#1f6feb",
        texture="metal",
        font_stack="japanese",
        letter_spacing="0.055em",
        digit_scale=0.86,
        letter_scale=1.0,
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_align="center",
        header_source="region",
        header_color="#164d2b",
        header_offset=0.07,
        region_position="inline",
        region_style="block",
        region_width=0.0,
        mount="holes",
        sheen=0.55,
        relief=0.3,
        grain=0.13,
        emblem="green_mark",
    ),
    # --- USA: 305x152 state-branded plate. The header carries the state's own name, so
    # no two states read the same, and the mounting is pressed screw holes.
    "us": PlateVisual(
        theme="us",
        plate_family="us_state",
        width_mm=PLATE_305x152[0],
        height_mm=PLATE_305x152[1],
        radius="10px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f0f2f5",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#2563eb",
        texture="enamel",
        font_stack="sans",
        letter_spacing="0.13em",
        group_gap="0.5em",
        digit_weight=600,
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_align="center",
        header_source="region",
        header_color="#1f2937",
        header_offset=0.09,
        region_position="none",
        region_style="none",
        region_width=0.0,
        mount="holes",
        sheen=0.6,
        relief=0.28,
        grain=0.1,
        emblem="state_tag",
    ),
    # --- Canada: wordmark top-left, short serial, no separate region compartment.
    "ca": PlateVisual(
        theme="ca",
        plate_family="americas_long",
        width_mm=PLATE_305x152[0],
        height_mm=PLATE_305x152[1],
        radius="9px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#eff2f6",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#d80621",
        texture="enamel",
        font_stack="sans",
        letter_spacing="0.09em",
        group_gap="0.5em",
        digit_weight=600,
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="CANADA",
        header_align="left",
        header_source="static",
        header_color="#d80621",
        header_offset=0.08,
        region_position="none",
        region_style="none",
        region_width=0.0,
        mount="holes",
        sheen=0.56,
        relief=0.28,
        grain=0.1,
        emblem="",
    ),
    # --- United Arab Emirates: 520x130 chrome-faced plate with the emirate name above
    # and the emirate number in a small side compartment.
    "ae": PlateVisual(
        theme="ae",
        plate_family="mideast",
        width_mm=PLATE_520x130[0],
        height_mm=PLATE_520x130[1],
        radius="6px",
        border_width="3px",
        background="#f7f9fc",
        background_alt="#e9eef4",
        border="#0f172a",
        text="#0b1220",
        muted="#64748b",
        accent="#c8a24a",
        texture="chrome",
        font_stack="wide",
        letter_spacing="0.07em",
        group_gap="0.7em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="holes",
        sheen=0.72,
        relief=0.36,
        grain=0.08,
        emblem="crest",
    ),
    "am": PlateVisual(
        theme="am",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#ffffff",
        background_alt="#f3f5f9",
        border="#1f2937",
        text="#0b1220",
        muted="#5b6474",
        accent="#d12d2d",
        texture="metal",
        font_stack="wide",
        letter_spacing="0.05em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.19,
        band_text="AM",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    "ge": PlateVisual(
        theme="ge",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#ffffff",
        background_alt="#f3f6f9",
        border="#1f2937",
        text="#0b1220",
        muted="#5b6474",
        accent="#e11d48",
        texture="metal",
        font_stack="condensed",
        letter_spacing="0.05em",
        group_gap="0.7em",
        band_position="left",
        band_color="#0f766e",
        band_width=0.19,
        band_text="GE",
        band_text_color="#ffffff",
        header="",
        header_source="none",
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    # --- Documented generic families ---------------------------------------
    #
    # A country shipped on one of these keeps its own printed code (its ISO alpha-2 in
    # the EU band) and its own surface colours, but shares a documented geometry. That
    # is an honest game layout, not a claim to reproduce any specific national scheme.
    "european": PlateVisual(
        theme="european",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fbfbfa",
        background_alt="#edeff2",
        border="#1a1a1a",
        text="#111827",
        muted="#4b5563",
        accent="#3b4a6b",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.19,
        band_text="",
        band_text_source="country_alpha2",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    "eu_long": PlateVisual(
        theme="eu_long",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#fbfbfa",
        background_alt="#edeff2",
        border="#1a1a1a",
        text="#111827",
        muted="#4b5563",
        accent="#3b4a6b",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.7em",
        band_position="left",
        band_color=EU_BAND,
        band_width=0.19,
        band_text="",
        band_text_source="country_alpha2",
        band_text_color=EU_BAND_TEXT,
        band_stars=True,
        header="",
        header_source="none",
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.48,
        relief=0.32,
        grain=0.15,
    ),
    "britain": PlateVisual(
        theme="britain",
        plate_family="uk",
        variant="front",
        width_mm=520,
        height_mm=111,
        radius="3px",
        border_width="2px",
        background="#f7f7f5",
        background_alt="#e8e8e4",
        border="#111111",
        text="#111111",
        muted="#3f3f46",
        accent="#c8102e",
        texture="reflective",
        font_stack="condensed",
        letter_spacing="0.07em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_source="none",
        region_position="none",
        region_style="none",
        region_width=0.0,
        mount="bolts",
        sheen=0.4,
        relief=0.3,
        grain=0.18,
    ),
    "mideast": PlateVisual(
        theme="mideast",
        plate_family="mideast",
        width_mm=PLATE_520x130[0],
        height_mm=PLATE_520x130[1],
        radius="6px",
        border_width="3px",
        background="#f7f9fc",
        background_alt="#e9eef4",
        border="#0f172a",
        text="#0b1220",
        muted="#64748b",
        accent="#c8a24a",
        texture="chrome",
        font_stack="wide",
        letter_spacing="0.07em",
        group_gap="0.7em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="holes",
        sheen=0.68,
        relief=0.36,
        grain=0.08,
        emblem="crest",
    ),
    "nordic": PlateVisual(
        theme="nordic",
        plate_family="eu_long",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="4px",
        border_width="3px",
        background="#f8faf8",
        background_alt="#ebf0ea",
        border="#0f172a",
        text="#0f172a",
        muted="#475569",
        accent="#0f766e",
        texture="metal",
        font_stack="euro",
        letter_spacing="0.045em",
        group_gap="0.75em",
        band_position="left",
        band_color="#0f172a",
        band_width=0.17,
        band_text="",
        band_text_source="country_alpha2",
        band_text_color="#ffffff",
        header="",
        header_source="none",
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.44,
        relief=0.32,
        grain=0.15,
    ),
    "latam": PlateVisual(
        theme="latam",
        plate_family="americas_long",
        width_mm=PLATE_305x152[0],
        height_mm=PLATE_305x152[1],
        radius="9px",
        border_width="2px",
        background="#fdfdfd",
        background_alt="#f0f2f5",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#16a34a",
        texture="enamel",
        font_stack="sans",
        letter_spacing="0.09em",
        group_gap="0.5em",
        digit_weight=600,
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_align="center",
        header_source="region",
        header_color="#1f2937",
        header_offset=0.09,
        region_position="none",
        region_style="none",
        region_width=0.0,
        mount="holes",
        sheen=0.56,
        relief=0.28,
        grain=0.1,
        emblem="",
    ),
    "seasia": PlateVisual(
        theme="seasia",
        plate_family="asia_wide",
        width_mm=440,
        height_mm=140,
        radius="6px",
        border_width="2px",
        background="#fbfbf8",
        background_alt="#eff1ee",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#0e7490",
        texture="metal",
        font_stack="wide",
        letter_spacing="0.075em",
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="holes",
        sheen=0.5,
        relief=0.3,
        grain=0.12,
        emblem="",
    ),
    "oceania": PlateVisual(
        theme="oceania",
        plate_family="asia_wide",
        width_mm=372,
        height_mm=134,
        radius="8px",
        border_width="2px",
        background="#fbfbf8",
        background_alt="#eff1ee",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#0f6f86",
        texture="metal",
        font_stack="wide",
        letter_spacing="0.09em",
        group_gap="0.55em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="holes",
        sheen=0.5,
        relief=0.3,
        grain=0.12,
        emblem="",
    ),
    "africa": PlateVisual(
        theme="africa",
        plate_family="asia_wide",
        width_mm=PLATE_520x110[0],
        height_mm=PLATE_520x110[1],
        radius="8px",
        border_width="2px",
        background="#fbfbf8",
        background_alt="#eff1ee",
        border="#1f2937",
        text="#0f172a",
        muted="#64748b",
        accent="#a16207",
        texture="metal",
        font_stack="wide",
        letter_spacing="0.075em",
        group_gap="0.6em",
        band_position="none",
        band_color=None,
        band_width=0.0,
        band_text="",
        header="",
        header_align="center",
        header_source="region",
        header_color="#334155",
        header_offset=0.08,
        region_position="badge",
        region_style="badge",
        region_width=0.12,
        mount="bolts",
        sheen=0.45,
        relief=0.3,
        grain=0.16,
        emblem="",
    ),
}

DEFAULT_VISUAL = PlateVisual(theme="european")


def visual_for(theme: str) -> PlateVisual:
    """Recipe for a theme key, falling back to the documented generic EU family."""
    return PLATE_VISUALS.get(theme, DEFAULT_VISUAL)


def band_text_for(visual: PlateVisual, *, alpha2: str = "", alpha3: str = "") -> str:
    """Resolve the code printed inside a country's side band.

    An EU-style band carries the country's own ISO alpha-2 code - Poland prints ``PL``,
    not a generic ``EU`` placeholder - so the country identifier is never a stand-in.
    A recipe that draws no band prints no band text, whatever its ``band_text_source``
    says - otherwise the client would render an identifier for a stripe that is not on
    the plate.
    """
    if visual.band_position == "none":
        return ""
    source = visual.band_text_source
    if source == "country_alpha2":
        return str(alpha2 or "").strip().upper()[:2]
    if source == "country_alpha3":
        return str(alpha3 or "").strip().upper()[:3]
    return visual.band_text


def region_text_for(visual: PlateVisual, *, alpha2: str = "", alpha3: str = "") -> str:
    """The identifier printed in the right-hand region compartment.

    On the Russian format that compartment carries the flag, ``RUS`` and the region code,
    so the alpha-3 code is the right legend there. Everything else prints nothing.
    """
    if visual.region_position != "right":
        return ""
    return str(alpha3 or "").strip().upper()[:3]


def serialize_visual(theme: str, *, alpha2: str = "", alpha3: str = "") -> dict[str, object]:
    """JSON-serialisable visual contract for the API.

    The payload is complete: the client can render a country's plate correctly with no
    knowledge of that country, and a new country needs no frontend change.
    """
    visual = visual_for(theme)
    data: dict[str, object] = {
        "theme": visual.theme,
        "plate_family": visual.plate_family,
        "variant": visual.variant,
        # Physical geometry, and the ratio derived from it.
        "width_mm": visual.width_mm,
        "height_mm": visual.height_mm,
        "aspect": visual.aspect,
        "radius": visual.radius,
        "border_width": visual.border_width,
        # Surface.
        "background": visual.background,
        "background_alt": visual.background_alt,
        "border": visual.border,
        "text": visual.text,
        "muted": visual.muted,
        "accent": visual.accent,
        "texture": visual.texture,
        # Typography.
        "font_stack": FONT_STACKS.get(visual.font_stack, visual.font_stack),
        "font_stack_key": visual.font_stack,
        "letter_spacing": visual.letter_spacing,
        "group_gap": visual.group_gap,
        "digit_scale": visual.digit_scale,
        "letter_scale": visual.letter_scale,
        "digit_weight": visual.digit_weight,
        # Country identifier.
        "band_position": visual.band_position,
        "band_color": visual.band_color,
        "band_width": visual.band_width,
        "band_text": band_text_for(visual, alpha2=alpha2, alpha3=alpha3),
        "band_text_source": visual.band_text_source,
        "band_text_color": visual.band_text_color,
        "band_stars": visual.band_stars,
        "band_flag": visual.band_flag,
        "band_emblem": visual.band_emblem,
        # Printed header.
        "header": visual.header,
        "header_align": visual.header_align,
        "header_source": visual.header_source,
        "header_color": visual.header_color or visual.muted,
        "header_offset": visual.header_offset,
        # Region placement.
        "region_position": visual.region_position,
        "region_style": visual.region_style,
        "region_badge": visual.region_badge,
        "region_width": visual.region_width,
        "region_flag": visual.region_flag,
        "region_text": region_text_for(visual, alpha2=alpha2, alpha3=alpha3),
        "show_flag": visual.show_flag,
        "show_region_flag": visual.show_region_flag,
        # Mounting hardware.
        "mount": visual.mount,
        "mount_color": visual.mount_color,
        "mount_size": visual.mount_size,
        # Finish.
        "gloss": visual.gloss,
        "sheen": visual.sheen,
        "relief": visual.relief,
        "grain": visual.grain,
        "emblem": visual.emblem,
    }
    data.update(visual.extra)
    return data


__all__ = [
    "DEFAULT_VISUAL",
    "EU_BAND",
    "EU_BAND_TEXT",
    "FONT_STACKS",
    "PLATE_VISUALS",
    "PLATE_305x152",
    "PLATE_330x165",
    "PLATE_520x110",
    "PLATE_520x112",
    "PLATE_520x130",
    "PlateVisual",
    "band_text_for",
    "region_text_for",
    "serialize_visual",
    "visual_for",
]
