export type Rarity = 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY' | 'MYTHIC' | 'SECRET';

export const RARITY_ORDER: readonly Rarity[] = [
  'COMMON',
  'UNCOMMON',
  'RARE',
  'EPIC',
  'LEGENDARY',
  'MYTHIC',
  'SECRET',
] as const;

/**
 * The country presentation recipe, exactly as the server sends it.
 *
 * The renderer draws what is here. Nothing about a country's plate shape, typography,
 * identifier band or region placement is decided in this codebase, so adding a country
 * needs no frontend change.
 *
 * Geometry note: `width_mm`/`height_mm` are the plate's real standardised size and
 * `aspect` is derived from them on the server. They are sent together so a client can
 * use either, but the millimetres are the source of truth - a Russian plate is
 * 520x112 mm (4.64:1), which is why it renders long and low rather than square.
 */
export interface PlateVisual {
  theme: string;
  /** Physical family key driving the renderer's structural template. */
  plate_family: string;
  /** Front/rear variant where a country distinguishes them. */
  variant: string;
  /** Real plate width in millimetres. */
  width_mm: number;
  /** Real plate height in millimetres. */
  height_mm: number;
  /** width_mm / height_mm, rounded. */
  aspect: number;
  radius: string;
  border_width: string;
  background: string;
  background_alt: string;
  border: string;
  text: string;
  muted: string;
  accent: string;
  texture: string;
  font_stack: string;
  font_stack_key: string;
  letter_spacing: string;
  group_gap: string;
  digit_scale: number;
  letter_scale: number;
  digit_weight: number;
  band_position: string;
  band_color: string | null;
  band_width: number;
  band_text: string;
  band_text_source: string;
  band_text_color: string;
  band_stars: boolean;
  /** `null`, or a key such as `"ru"` for a flag drawn as vectors. */
  band_flag: string | null;
  band_emblem: string;
  header: string;
  header_align: string;
  /** `region` means "print the region's own name" - a US state's name, for instance. */
  header_source: string;
  header_color: string;
  /** Vertical offset of the header as a fraction of the plate height. */
  header_offset: number;
  region_position: string;
  region_style: string;
  /** Printed width of the right-hand region compartment, as a fraction of plate width. */
  region_width: number;
  /** Whether that compartment prints the country's flag above the code. */
  region_flag: boolean;
  /** The code printed in the compartment, resolved server-side (e.g. `RUS`). */
  region_text: string;
  show_flag: boolean;
  show_region_flag: boolean;
  /** Mounting hardware: `bolts` | `holes` | `none`. */
  mount: string;
  mount_color: string;
  /** Size of one mounting feature as a fraction of plate height. */
  mount_size: number;
  gloss: boolean;
  sheen: number;
  /** Raised-lettering relief, 0..1. */
  relief: number;
  /** Surface grain, 0..1. */
  grain: number;
  emblem: string;
  /** Compatibility alias for the previous contract. */
  region_badge?: boolean;
  /** Compatibility alias: the old bolt count. Derived from `mount` by the renderer. */
  bolts?: number;
}

export interface PlateCountry {
  code: string;
  /** ISO 3166-1 alpha-2 code, for share links and deep links. */
  iso_alpha2?: string;
  name_en: string;
  name_ru: string;
  flag: string;
}

export interface PlateRegion {
  code: string;
  name_en: string;
  name_ru: string;
}

export interface PlateDiscoverer {
  display_name: string;
  username: string | null;
  photo_url: string | null;
}

/**
 * The kinds of collectible a player can hunt.
 *
 * NUMORA has exactly two physical kinds: a vehicle registration plate and a SIM
 * card carrying a synthetic number. There is no phone-number collectible - a number
 * is information printed on a card, never an object in its own right.
 *
 * One loop: every kind is rolled, owned, duplicated, sold and shared the same way.
 * The server decides which kind a roll produces; the client only ever sends a
 * *filter*.
 */
export type CollectibleKind = 'VEHICLE_PLATE' | 'SIM_CARD';

export const COLLECTIBLE_KINDS: readonly CollectibleKind[] = ['VEHICLE_PLATE', 'SIM_CARD'] as const;

/**
 * Type-specific payload stored on a SIM card.
 *
 * Every number here is synthetic: generated by the backend and printed on the card.
 * The client renders it and never composes one.
 */
export interface SimCardDetails {
  /** Stable provider code from the catalogue. */
  operator_code: string;
  operator: string;
  operator_local: string;
  /** False marks a documented game brand, so nothing implies a real carrier. */
  operator_is_real: boolean;
  operator_visual: string;
  operator_accent: string;
  /** Game balance numbers, not claims about the operator's real tariffs or market. */
  rarity_modifier: number;
  value_modifier: number;
  series: string;
  edition: string;
  /** The number the backend generated and printed on the card. */
  synthetic_number: string;
  calling_code: string;
  synthetic: boolean;
}

/** One printed group of a collectible, with the typography its country uses. */
export type PlateSegmentKind = 'letter' | 'digit' | 'region' | 'mixed' | 'mark';

/** Canonical collectible payload returned by every collectible endpoint. */
export interface PlateCard {
  id: number;
  plate_text: string;
  normalized_text: string;
  display_segments: string[];
  /** Whether a space precedes each group. segments + gaps rebuild `plate_text` exactly. */
  display_segment_gaps: boolean[];
  display_segment_kinds: PlateSegmentKind[];
  letters: string[];
  numbers: string[];
  plate_type: string;
  /** The collectible kind. Absent only on payloads cached before the SIM line. */
  kind?: CollectibleKind;
  rarity: Rarity;
  rarity_score: number;
  rarity_color: string;
  reasons: string[];
  reason_labels: string[];
  traits: string[];
  tags: string[];
  story: string;
  is_secret: boolean;
  season_code: string | null;
  discovery_count: number;
  first_discovered_at: string | null;
  first_discoverer: PlateDiscoverer | null;
  collector_value: number;
  currency_code: string;
  currency_symbol: string;
  dealer_value: number;
  country: PlateCountry;
  region: PlateRegion | null;
  template: { code: string; pattern: string };
  visual: PlateVisual;
  /** Present for SIM cards, `null` for vehicle plates. */
  details: SimCardDetails | null;
  /**
   * How this country prints its SIM cards, when the payload carries it. Present so the
   * reveal can group the printed number the way the country does; absent means the card
   * falls back to grouping the printed string itself.
   */
  sim_config?: SimCardConfig | null;
  owned: boolean;
  duplicate_count: number;
  /** Copies already sold to the dealer; the final copy stays protected. */
  copies_sold: number;
  is_favorite: boolean;
  is_new: boolean;
  /** What one duplicate copy sells for, shown next to SELL DUPLICATES. */
  sale_value: number;
  acquired_at: string | null;
}

/** One entry of the country atlas / selector. */
export interface CountrySummary {
  code: string;
  iso_alpha2?: string;
  name_en: string;
  name_ru: string;
  flag: string;
  region_group: string;
  currency_code: string;
  currency_symbol: string;
  calling_code?: string;
  visual?: PlateVisual;
  collected: number;
  total: number;
  progress: number;
  percent: number;
  best_rarity: Rarity | null;
  regions_collected: number;
  regions_total: number;
  completed: boolean;
  sort_order: number;
  is_active: boolean;
  /** Whether a roll may currently produce this country. */
  is_playable: boolean;
}

export interface SimOperator {
  code: string;
  name: string;
  name_local: string;
}

/** One mobile operator brand a country may print, with its two *game* modifiers. */
export interface SimProviderItem {
  code: string;
  brand: string;
  local_name: string;
  rarity_modifier: number;
  value_modifier: number;
  visual: string;
  accent: string;
  is_real_brand: boolean;
}

/**
 * How one country prints its collectible SIM cards. Purely presentational: the number on
 * a card is generated by the backend and is never composed here.
 */
export interface SimCardConfig {
  calling_code: string;
  groups: number[];
  providers: SimProviderItem[];
  /** Compatibility alias for the previous contract, derived from `providers`. */
  operators: SimOperator[];
  editions: string[];
  synthetic: boolean;
}

/** One completion set inside a country: Standard / Regional / Rare Formats / Special. */
export interface CountrySection {
  code: string;
  name_en: string;
  name_ru: string;
  collected: number;
  total: number;
  remaining: number;
  progress: number;
  completed: boolean;
}

export interface CountryCompletion {
  country_code: string;
  sections: CountrySection[];
  collected: number;
  total: number;
  remaining: number;
  progress: number;
  completed: boolean;
}

/**
 * One objective, machine-readable.
 *
 * The backend sends a stable code plus the counts behind it; the sentence itself is
 * assembled through i18n, so no backend copy is ever shown to a player.
 */
export interface NextTarget {
  code: string;
  country_code: string;
  country_name_en: string;
  country_name_ru: string;
  country_flag: string;
  current: number;
  target: number;
  remaining: number;
  progress: number;
  section_code: string | null;
  section_name_en: string | null;
  section_name_ru: string | null;
  mission_code: string | null;
  album_code: string | null;
  rarity: string | null;
  achievement_code: string | null;
  reward_coins: number;
  providers_total: number;
}

/**
 * The authoritative roll economy.
 *
 * The client renders the roll button from this and keeps no economy of its own: the
 * normal bank, the bonus bank, the cap and the regeneration countdown all come from the
 * server, which is the only thing allowed to decide them.
 */
export interface RollBalance {
  rolls_remaining: number;
  normal_rolls: number;
  bonus_rolls: number;
  daily_allowance: number;
  bank_cap: number;
  resets_at: string;
  next_roll_at: string | null;
  seconds_to_next_roll: number;
  regen_minutes: number;
}

export interface CountryDetail extends CountrySummary {
  templates: Array<{
    code: string;
    pattern: string;
    plate_type: string;
    rarity_floor: string;
    weight: number;
  }>;
  /** The country's completion sets plus its overall total. */
  completion?: CountryCompletion;
  next_target?: NextTarget;
}

/** The full country payload the selector and the detail screen need. */
/** One region of a country, as offered by the collection's region filter. */
export interface PlateRegionOption {
  code: string;
  name_en: string;
  name_ru: string;
  sort_order?: number;
}

export interface CountryCard extends CountrySummary {
  id?: number;
  is_active_country: boolean;
  sim: SimCardConfig;
  /** The country's regions, for the collection's region filter. */
  regions?: PlateRegionOption[];
  completion?: CountryCompletion;
  next_target?: NextTarget;
}

export interface CountryListResponse {
  items: CountrySummary[];
  total: number;
  playable_total: number;
  locked_total: number;
  region_groups: string[];
  query: string | null;
  offset: number;
  limit: number;
  active_code: string | null;
}

export interface ActiveCountryResponse {
  country: CountryCard | null;
  code: string | null;
  playable_total: number;
  locked_total: number;
}

export interface AchievementBadge {
  code: string;
  name: string;
  description: string;
  icon: string;
  reward_coins: number;
}

export interface CollectorLevel {
  level: number;
  title_en: string;
  title_ru: string;
  xp: number;
  xp_into_level: number;
  xp_for_level: number;
  progress: number;
}

export interface PremiumState {
  active: boolean;
  tier: string | null;
  expires_at: string | null;
  perks: string[];
}

export interface UserProfile {
  id: number;
  telegram_id: number;
  username: string | null;
  first_name: string;
  last_name: string;
  display_name: string;
  photo_url: string | null;
  language_code: string | null;
  role: string;
  is_admin: boolean;
  is_banned: boolean;
  coins: number;
  total_earned: number;
  total_spent: number;
  total_rolls: number;
  containers_opened: number;
  /** Legacy alias of ``plates_count`` kept for older screens. */
  unique_numbers: number;
  plates_count: number;
  countries_count: number;
  regions_count: number;
  first_discoveries_count: number;
  duplicates_sold_count: number;
  collection_progress: number;
  collection_target: number;
  collector_level: CollectorLevel;
  best_value: number;
  best_rarity: Rarity | null;
  best_collector_value: number;
  best_plate_id: number | null;
  best_plate_text: string;
  referrals_count: number;
  shares_count: number;
  challenges_completed: number;
  current_streak: number;
  longest_streak: number;
  rolls_remaining: number;
  daily_allowance: number;
  daily_resets_at: string | null;
  can_claim_daily: boolean;
  /** The normal, regenerating bank. */
  normal_rolls?: number;
  /** Rolls granted above the normal bank; never consumed by regeneration. */
  bonus_rolls?: number;
  /** When the next passive roll lands, or `null` while the bank is full. */
  next_roll_at?: string | null;
  seconds_to_next_roll?: number;
  roll_regen_minutes?: number;
  premium: PremiumState;
  supporter: boolean;
  season_pass_active: boolean;
  equipped_title: string | null;
  equipped_cosmetics: string[];
  created_at: string | null;
  last_seen_at: string | null;
}

/**
 * One synthetic frame of the roll reel.
 *
 * A frame is a *picture*, never a result. It is generated by the backend from the real
 * catalogue with a separate RNG stream, is not persisted, and is not scored, valued or
 * granted. The real collectible arrives separately as the roll's `plate`, which is the
 * only thing the reel settles onto.
 */
export interface ReelFrame {
  plate_text: string;
  display_segments: string[];
  display_segment_gaps: boolean[];
  display_segment_kinds: string[];
  /** The same recipe contract the real card carries, so a frame renders identically. */
  visual: PlateVisual;
  /** `VEHICLE_PLATE` or `SIM_CARD` - the two collectible kinds, nothing else. */
  kind: string;
  country_code: string;
  country_name_en: string;
  country_flag: string;
}

/** Result of POST /api/roll - the collectible reveal payload. */
export interface PlateRollResult {
  success: true;
  roll_id: number;
  plate: PlateCard;
  rarity: Rarity;
  natural_rarity: Rarity;
  luck_rarity: Rarity;
  rarity_score: number;
  is_duplicate: boolean;
  is_first_discovery: boolean;
  is_new_country: boolean;
  is_new_region: boolean;
  numora_awarded: number;
  balance: number;
  rolls_remaining: number;
  sale_value: number;
  collector_level: number;
  /** The roll economy after this roll, including the regeneration countdown. */
  rolls?: RollBalance;
  /** Exactly one objective, so the player is never left without a next step. */
  next_target?: NextTarget | null;
  /**
   * Synthetic frames for the reel animation, generated server-side and never persisted.
   *
   * The reel scrolls through these and settles on `plate`. They are previews only: the
   * backend has already generated, scored and committed `plate` before this array was
   * built, and no frame is stored, valued or granted.
   */
  reel?: ReelFrame[];
  missions_completed: Array<{ code: string; name_en?: string; name_ru?: string }>;
  albums_completed: Array<{ code: string; name_en?: string; name_ru?: string }>;
  unlocked_achievements: AchievementBadge[];
  event: Record<string, unknown> | null;
  replayed: boolean;
  share_start_param: string;
  // Compatibility aliases for the legacy roll client.
  value: number;
  coins_awarded: number;
  conversion_value: number;
  number: PlateCard;
}

/**
 * What the player asked for.
 *
 * This is the *only* thing the client may influence about a roll. The number,
 * its rarity, its value, whether it is a first discovery and the reward are all
 * decided server-side - sending any of them from here would be a forgery attempt
 * the backend ignores.
 */
export interface HuntFilter {
  kind?: CollectibleKind | null;
  country_code?: string | null;
}
export interface GarageData {
  best: PlateCard | null;
  recent: PlateCard | null;
  plates_count: number;
  countries_count: number;
  regions_count: number;
  first_discoveries: number;
  best_collector_value: number;
  /** Fraction of the playable world the player has collected. */
  world_progress: number;
  /** The world target, so a progress bar never reconstructs it from the fraction. */
  collection_target?: number;
  playable_countries?: number;
  locked_countries?: number;
  total_dealer_value?: number;
  level: CollectorLevel;
  event: GlobalEvent | null;
  albums_completed: AlbumProgress[];
  equipped_cosmetics: string[];
  /** The country the player is hunting right now. */
  hunt_country?: string | null;
  hunt_country_name_en?: string;
  hunt_country_name_ru?: string;
  hunt_country_flag?: string;
  /** The hunt country's completion sets. */
  country_progress?: CountryCompletion | null;
  /** Exactly one objective. */
  next_target?: NextTarget;
  /** The authoritative roll economy, including the regeneration countdown. */
  rolls?: RollBalance;
}

export interface GlobalEvent {
  code: string;
  name_en: string;
  name_ru: string;
  flag: string;
  country_multipliers: Record<string, number>;
  ends_at: string | null;
  reward_coins: number;
  reward_title: string | null;
  is_event: boolean;
}

export interface AlbumProgress {
  code: string;
  name_en: string;
  name_ru: string;
  description_en: string;
  description_ru: string;
  icon: string;
  kind: string;
  collected: number;
  total: number;
  progress: number;
  percent: number;
  completed: boolean;
  reward_coins: number;
  reward_title: string | null;
}

export interface DailyStatus {
  rolls_remaining: number;
  daily_allowance: number;
  resets_at: string;
  streak: number;
  can_claim: boolean;
  claim_reward_coins: number;
  /** The normal, regenerating bank. */
  normal_rolls: number;
  /** Rolls granted above the normal bank; never consumed by regeneration. */
  bonus_rolls: number;
  /** When the next passive roll lands, or `null` while the bank is full. */
  next_roll_at: string | null;
  seconds_to_next_roll: number;
  regen_minutes: number;
}

export interface DailyClaimResult {
  success: true;
  coins_granted: number;
  rolls_granted: number;
  streak: number;
  balance: number;
  unlocked_achievements: AchievementBadge[];
}
export interface ContainerCard {
  code: string;
  name: string;
  description: string;
  price: number;
  minimum_rarity: Rarity;
  rarity_weights: Record<string, number>;
  accent: string;
  animation: string;
  premium_only: boolean;
  locked: boolean;
  affordable: boolean;
  granted_by_premium: boolean;
}

export interface ContainerOpenResult {
  success: true;
  opening_id: number;
  container: string;
  number: NumberCardLegacy;
  is_duplicate: boolean;
  value: number;
  balance: number;
  conversion_value: number;
  unlocked_achievements: AchievementBadge[];
  replayed: boolean;
}

/** Shape of a legacy 4-digit number card (boxes still open numbers). */
export interface NumberCardLegacy {
  number: string;
  rarity: Rarity;
  value: number;
  traits: string[];
  tags: string[];
  story: string;
  is_special: boolean;
  discovery_count: number;
  duplicate_count: number;
  owned: boolean;
  acquired_at: string | null;
}

export interface CollectionResponse {
  items: PlateCard[];
  page: number;
  page_size: number;
  total: number;
  has_more: boolean;
  rarity_breakdown: Record<string, number>;
  progress: number;
  target: number;
  duplicates_count: number;
  total_dealer_value: number;
  /** The country the list was filtered by; `null` means the whole world. */
  country_code?: string | null;
}

export interface WorldResponse {
  countries: CountrySummary[];
  total_collected: number;
  total_plates: number;
  progress: number;
  event: GlobalEvent | null;
  offset: number;
  limit: number;
  countries_total: number;
  playable_total: number;
  locked_total: number;
}

export interface SaleResult {
  plate_id: number;
  plate_text: string;
  copies_sold: number;
  numora_gained: number;
  duplicates_left: number;
  balance: number;
}

export interface SellAllResult {
  plates_sold: number;
  copies_sold: number;
  numora_gained: number;
  balance: number;
}

export interface LeaderboardEntry {
  user_id: number;
  display_name: string;
  username: string | null;
  photo_url: string | null;
  score: number;
  rolls: number;
}

export interface LeaderboardBoard {
  category: string;
  period: string;
  label: string;
  entries: LeaderboardEntry[];
  you: number | null;
}

export interface AchievementItem {
  code: string;
  name: string;
  description: string;
  icon: string;
  threshold: number;
  progress: number;
  reward_coins: number;
  unlocked: boolean;
  unlocked_at: string | null;
}
export interface PlayerRef {
  display_name: string;
  username: string | null;
  photo_url: string | null;
}

export interface ChallengeItem {
  code: string;
  status: 'PENDING' | 'COMPLETED' | 'EXPIRED' | 'DECLINED';
  challenger: PlayerRef | null;
  opponent: PlayerRef | null;
  challenger_plate_id: number | null;
  challenger_plate_text: string | null;
  challenger_rarity: Rarity | null;
  challenger_score: number;
  opponent_plate_id: number | null;
  opponent_plate_text: string | null;
  opponent_rarity: Rarity | null;
  opponent_score: number;
  winner_id: number | null;
  expires_at: string | null;
  completed_at: string | null;
  link: string | null;
}

export interface ReferralSummary {
  referral_code: string;
  referral_link: string;
  total: number;
  activated: number;
  pending: number;
  coins_earned: number;
  reward_coins: number;
  reward_rolls: number;
  items: Array<{
    status: string;
    username: string | null;
    display_name: string;
    photo_url: string | null;
    reward_coins: number;
    created_at: string;
    activated_at: string | null;
  }>;
}

export interface SeasonItem {
  code: string;
  name: string;
  description: string;
  start_date: string | null;
  end_date: string | null;
  is_active: boolean;
  is_over: boolean;
  special_numbers: string[];
  rewards: Record<string, unknown>;
}

export interface ProductItem {
  code: string;
  name: string;
  description: string;
  stars_price: number;
  grant_type: string;
}

export interface InvoiceResult {
  success: true;
  payment_id: number;
  provider: string;
  product_code: string;
  amount: number;
  currency: string;
  status: string;
  invoice_link: string | null;
  mock_confirm_url: string | null;
}

export interface PlateShareResult {
  plate_id: number;
  plate_text: string;
  rarity: Rarity;
  rarity_score: number;
  collector_value: number;
  currency_symbol: string;
  dealer_value: number;
  start_param: string;
  mini_app_link: string;
  share_text_en: string;
  share_text_ru: string;
}

export interface StartContext {
  raw: string | null;
  referral_telegram_id: number | null;
  shared_number: string | null;
  shared_plate_id: number | null;
  country_code: string | null;
  season_code: string | null;
  challenge_code: string | null;
}

export interface AuthResponse {
  success: true;
  access_token: string;
  token_type: string;
  expires_in: number;
  is_new_user: boolean;
  user: UserProfile;
  start_context: StartContext;
}
