"""initial schema

Revision ID: b830b9d498eb
Revises: 
Create Date: 2026-10-03 20:39:02.682436

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b830b9d498eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_achievements_created_at'), ['created_at'], unique=False)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rarity_weights', sa.JSON(), nullable=False),
    sa.Column('minimum_rarity', sa.String(length=16), nullable=False),
    sa.Column('accent', sa.String(length=16), nullable=False),
    sa.Column('animation', sa.String(length=16), nullable=False),
    sa.Column('premium_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_containers'))
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_containers_created_at'), ['created_at'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stars_price', sa.Integer(), nullable=False),
    sa.Column('grant_type', sa.String(length=16), nullable=False),
    sa.Column('grant_payload', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('special_numbers', sa.JSON(), nullable=False),
    sa.Column('rewards', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_seasons_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('is_telegram_premium', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('total_rolls', sa.Integer(), nullable=False),
    sa.Column('containers_opened', sa.Integer(), nullable=False),
    sa.Column('unique_numbers_count', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('challenges_completed', sa.Integer(), nullable=False),
    sa.Column('referrals_count', sa.Integer(), nullable=False),
    sa.Column('best_value', sa.BigInteger(), nullable=False),
    sa.Column('best_rarity', sa.String(length=16), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_daily_claim_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_roll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_rolls_used', sa.Integer(), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bonus_rolls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_best_value', ['best_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index('ix_users_total_rolls', ['total_rolls'], unique=False)
        batch_op.create_index('ix_users_unique_numbers', ['unique_numbers_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_analytics_name_created', ['name', 'created_at'], unique=False)

    op.create_table('daily_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claimed_on', sa.Date(), nullable=False),
    sa.Column('rolls_granted', sa.Integer(), nullable=False),
    sa.Column('coins_granted', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_rewards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_rewards')),
    sa.UniqueConstraint('user_id', 'claimed_on', name='uq_daily_rewards_user_claimed_on')
    )
    with op.batch_alter_table('daily_rewards', schema=None) as batch_op:
        batch_op.create_index('ix_daily_rewards_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('user_id', 'scope', 'key', name='uq_idempotency_user_scope_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_user_id'), ['user_id'], unique=False)

    op.create_table('numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value_str', sa.String(length=4), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('base_value', sa.BigInteger(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('discovery_count', sa.Integer(), nullable=False),
    sa.Column('first_discovered_by_id', sa.Integer(), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['first_discovered_by_id'], ['users.id'], name=op.f('fk_numbers_first_discovered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numbers'))
    )
    with op.batch_alter_table('numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_numbers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_numbers_rarity'), ['rarity'], unique=False)
        batch_op.create_index('ix_numbers_rarity_value', ['rarity', 'value_int'], unique=False)
        batch_op.create_index(batch_op.f('ix_numbers_value_int'), ['value_int'], unique=False)
        batch_op.create_index(batch_op.f('ix_numbers_value_str'), ['value_str'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('product_code', sa.String(length=48), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('invoice_payload', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('refunded_amount', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_payments_provider_external_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_param', sa.String(length=64), nullable=True),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('reward_rolls', sa.Integer(), nullable=False),
    sa.Column('reward_paid', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name=op.f('fk_referrals_referred_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referrals_referrer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('referred_id', name=op.f('uq_referrals_referred_id'))
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index('ix_referrals_referrer_status', ['referrer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_status'), ['status'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievements_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_unlocked_at'), ['unlocked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions')),
    sa.UniqueConstraint('idempotency_key', name='uq_wallet_transactions_idempotency_key')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_wallet_tx_user_type_created', ['user_id', 'type', 'created_at'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.BigInteger(), nullable=False),
    sa.Column('total_earned', sa.BigInteger(), nullable=False),
    sa.Column('total_spent', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_wallets_user_id'))
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_created_at'), ['created_at'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('challenger_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('challenger_number_id', sa.Integer(), nullable=False),
    sa.Column('opponent_number_id', sa.Integer(), nullable=True),
    sa.Column('challenger_rarity', sa.String(length=16), nullable=False),
    sa.Column('challenger_value', sa.Integer(), nullable=False),
    sa.Column('opponent_rarity', sa.String(length=16), nullable=True),
    sa.Column('opponent_value', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], name=op.f('fk_challenges_challenger_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenger_number_id'], ['numbers.id'], name=op.f('fk_challenges_challenger_number_id_numbers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], name=op.f('fk_challenges_opponent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opponent_number_id'], ['numbers.id'], name=op.f('fk_challenges_opponent_number_id_numbers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_challenges_winner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_challenger_id'), ['challenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_challenges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_opponent_id'), ['opponent_id'], unique=False)
        batch_op.create_index('ix_challenges_opponent_status', ['opponent_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_status'), ['status'], unique=False)

    op.create_table('container_openings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.BigInteger(), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name=op.f('fk_container_openings_container_id_containers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], name=op.f('fk_container_openings_number_id_numbers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_container_openings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_openings')),
    sa.UniqueConstraint('idempotency_key', name='uq_container_openings_idempotency_key')
    )
    with op.batch_alter_table('container_openings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_openings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_openings_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_openings_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('discoveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_first_discovery', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], name=op.f('fk_discoveries_number_id_numbers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discoveries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discoveries'))
    )
    with op.batch_alter_table('discoveries', schema=None) as batch_op:
        batch_op.create_index('ix_discoveries_number_created', ['number_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveries_number_id'), ['number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveries_user_id'), ['user_id'], unique=False)

    op.create_table('premium_entitlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_premium_entitlements_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_premium_entitlements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_entitlements'))
    )
    with op.batch_alter_table('premium_entitlements', schema=None) as batch_op:
        batch_op.create_index('ix_entitlements_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_entitlements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_entitlements_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_entitlements_user_id'), ['user_id'], unique=False)

    op.create_table('rolls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('natural_rarity', sa.String(length=16), nullable=False),
    sa.Column('luck_rarity', sa.String(length=16), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('coins_awarded', sa.BigInteger(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_first_discovery', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], name=op.f('fk_rolls_number_id_numbers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rolls_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rolls')),
    sa.UniqueConstraint('idempotency_key', name='uq_rolls_idempotency_key')
    )
    with op.batch_alter_table('rolls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rolls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rolls_rarity'), ['rarity'], unique=False)
        batch_op.create_index('ix_rolls_rarity_created', ['rarity', 'created_at'], unique=False)
        batch_op.create_index('ix_rolls_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rolls_user_id'), ['user_id'], unique=False)

    op.create_table('share_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('start_param', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], name=op.f('fk_share_events_number_id_numbers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_events'))
    )
    with op.batch_alter_table('share_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('coins_earned', sa.BigInteger(), nullable=False),
    sa.Column('first_acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], name=op.f('fk_user_numbers_number_id_numbers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_numbers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_numbers')),
    sa.UniqueConstraint('user_id', 'number_id', name='uq_user_numbers_user_number')
    )
    with op.batch_alter_table('user_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_numbers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_numbers_number_id'), ['number_id'], unique=False)
        batch_op.create_index('ix_user_numbers_user_acquired', ['user_id', 'first_acquired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_numbers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_numbers_user_id'))
        batch_op.drop_index('ix_user_numbers_user_acquired')
        batch_op.drop_index(batch_op.f('ix_user_numbers_number_id'))
        batch_op.drop_index(batch_op.f('ix_user_numbers_created_at'))

    op.drop_table('user_numbers')
    with op.batch_alter_table('share_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_share_events_created_at'))

    op.drop_table('share_events')
    with op.batch_alter_table('rolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rolls_user_id'))
        batch_op.drop_index('ix_rolls_user_created')
        batch_op.drop_index('ix_rolls_rarity_created')
        batch_op.drop_index(batch_op.f('ix_rolls_rarity'))
        batch_op.drop_index(batch_op.f('ix_rolls_created_at'))

    op.drop_table('rolls')
    with op.batch_alter_table('premium_entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premium_entitlements_user_id'))
        batch_op.drop_index(batch_op.f('ix_premium_entitlements_expires_at'))
        batch_op.drop_index(batch_op.f('ix_premium_entitlements_created_at'))
        batch_op.drop_index('ix_entitlements_user_active')

    op.drop_table('premium_entitlements')
    with op.batch_alter_table('discoveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discoveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_discoveries_number_id'))
        batch_op.drop_index('ix_discoveries_number_created')

    op.drop_table('discoveries')
    with op.batch_alter_table('container_openings', schema=None) as batch_op:
        batch_op.drop_index('ix_openings_user_created')
        batch_op.drop_index(batch_op.f('ix_container_openings_user_id'))
        batch_op.drop_index(batch_op.f('ix_container_openings_created_at'))

    op.drop_table('container_openings')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_status'))
        batch_op.drop_index('ix_challenges_opponent_status')
        batch_op.drop_index(batch_op.f('ix_challenges_opponent_id'))
        batch_op.drop_index(batch_op.f('ix_challenges_created_at'))
        batch_op.drop_index(batch_op.f('ix_challenges_code'))
        batch_op.drop_index(batch_op.f('ix_challenges_challenger_id'))

    op.drop_table('challenges')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_created_at'))

    op.drop_table('wallets')
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_wallet_tx_user_type_created')
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_created_at'))

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievements_unlocked_at'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_status'))
        batch_op.drop_index('ix_referrals_referrer_status')
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_created_at'))

    op.drop_table('referrals')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_product_code'))
        batch_op.drop_index(batch_op.f('ix_payments_external_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_numbers_value_str'))
        batch_op.drop_index(batch_op.f('ix_numbers_value_int'))
        batch_op.drop_index('ix_numbers_rarity_value')
        batch_op.drop_index(batch_op.f('ix_numbers_rarity'))
        batch_op.drop_index(batch_op.f('ix_numbers_created_at'))

    op.drop_table('numbers')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_user_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('daily_rewards', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_rewards_user_created')

    op.drop_table('daily_rewards')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_name_created')
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index('ix_users_unique_numbers')
        batch_op.drop_index('ix_users_total_rolls')
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index('ix_users_best_value')

    op.drop_table('users')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_is_active'))
        batch_op.drop_index(batch_op.f('ix_seasons_created_at'))
        batch_op.drop_index(batch_op.f('ix_seasons_code'))

    op.drop_table('seasons')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_products_code'))

    op.drop_table('products')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_created_at'))
        batch_op.drop_index(batch_op.f('ix_containers_code'))

    op.drop_table('containers')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_created_at'))
        batch_op.drop_index(batch_op.f('ix_achievements_code'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
