import type {
  CountryCard,
  GarageData,
  NextTarget,
  PlateCard,
  PlateRollResult,
  PlateVisual,
  RollBalance,
  SimCardDetails,
  UserProfile,
} from '@/types';

/**
 * Test fixtures for the canonical collectible contract.
 *
 * Every fixture here is shaped like a real API payload, including the fields the newer
 * systems rely on - the full plate recipe, the grouped segments with their gaps, the
 * provider block on a SIM card and the roll economy. A fixture that omits them would let
 * a component "pass" while rendering nothing, which is exactly the class of bug these
 * tests exist to catch.
 */

/** The Russian plate recipe, verbatim in the shape the backend sends. */
export const ruVisual: PlateVisual = {
  theme: 'ru',
  plate_family: 'cis_right_region',
  variant: 'standard',
  // GOST R 50577-2018 type 1: 520x112 mm. The ratio is derived from these on the server.
  width_mm: 520,
  height_mm: 112,
  aspect: 4.643,
  radius: '4px',
  border_width: '2px',
  background: '#ffffff',
  background_alt: '#f4f5f7',
  border: '#111111',
  text: '#0a0a0a',
  muted: '#5b6169',
  accent: '#2f6bd8',
  texture: 'metal',
  font_stack: "'Roboto Condensed', 'PT Sans Narrow', 'Arial Narrow', sans-serif",
  font_stack_key: 'cyrillic',
  letter_spacing: '0.055em',
  group_gap: '0.6em',
  digit_scale: 1.0,
  letter_scale: 0.93,
  digit_weight: 700,
  band_position: 'none',
  band_color: null,
  band_width: 0.0,
  band_text: '',
  band_text_source: 'country_alpha3',
  band_text_color: '#111111',
  band_stars: false,
  band_flag: null,
  band_emblem: '',
  header: '',
  header_align: 'center',
  header_source: 'none',
  header_color: '#5b6169',
  header_offset: 0.08,
  region_position: 'right',
  region_style: 'block',
  region_width: 0.132,
  region_flag: true,
  region_text: 'RUS',
  show_flag: true,
  show_region_flag: true,
  mount: 'bolts',
  mount_color: '#8a9099',
  mount_size: 0.11,
  gloss: true,
  sheen: 0.5,
  relief: 0.34,
  grain: 0.14,
  emblem: '',
};

/** The Polish recipe: an EU long plate with the PL band and the star ring. */
export const polVisual: PlateVisual = {
  ...ruVisual,
  theme: 'pol',
  plate_family: 'eu_long',
  width_mm: 520,
  height_mm: 110,
  aspect: 4.727,
  border_width: '3px',
  background: '#fbfbf8',
  background_alt: '#ebedef',
  border: '#1a1a1a',
  text: '#111827',
  accent: '#dc2626',
  font_stack_key: 'euro',
  font_stack: "'Arial Narrow', 'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif",
  letter_spacing: '0.045em',
  letter_scale: 0.92,
  group_gap: '0.7em',
  band_position: 'left',
  band_color: '#003399',
  band_width: 0.19,
  band_text: 'PL',
  band_text_source: 'static',
  band_text_color: '#ffd300',
  band_stars: true,
  header_align: 'center',
  region_position: 'badge',
  region_style: 'badge',
  region_width: 0.12,
  region_flag: false,
  region_text: '',
  mount: 'bolts',
  sheen: 0.52,
  relief: 0.32,
  grain: 0.15,
  emblem: '',
};

/** The US recipe: state-name header, pressed screw holes, near-square. */
export const usVisual: PlateVisual = {
  ...ruVisual,
  theme: 'us',
  plate_family: 'us_state',
  width_mm: 305,
  height_mm: 152,
  aspect: 2.007,
  radius: '10px',
  background: '#fdfdfd',
  background_alt: '#f0f2f5',
  border: '#1f2937',
  text: '#0f172a',
  muted: '#64748b',
  accent: '#2563eb',
  texture: 'enamel',
  font_stack: "'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
  font_stack_key: 'sans',
  letter_spacing: '0.13em',
  letter_scale: 0.92,
  group_gap: '0.5em',
  digit_weight: 600,
  band_position: 'none',
  band_color: null,
  band_width: 0.0,
  band_text: '',
  header_source: 'region',
  header_color: '#1f2937',
  header_align: 'center',
  header_offset: 0.09,
  region_position: 'none',
  region_style: 'none',
  region_width: 0.0,
  region_flag: false,
  region_text: '',
  mount: 'holes',
  sheen: 0.6,
  relief: 0.28,
  grain: 0.1,
  emblem: 'state_tag',
};

export function simDetails(overrides: Partial<SimCardDetails> = {}): SimCardDetails {
  return {
    operator_code: 'mts',
    operator: 'MTS',
    operator_local: 'МТС',
    operator_is_real: true,
    operator_visual: 'waveform',
    operator_accent: '#ff0032',
    rarity_modifier: 1.06,
    value_modifier: 1.1,
    series: 'N-42',
    edition: 'APEX',
    synthetic_number: '+7 900 123 45 67',
    calling_code: '+7',
    synthetic: true,
    ...overrides,
  };
}

export function plate(overrides: Partial<PlateCard> = {}): PlateCard {
  return {
    id: 777,
    plate_text: 'A777BC 777',
    normalized_text: 'a777bc777',
    // Groups plus gaps reconstruct `plate_text` exactly.
    display_segments: ['A777BC', '777'],
    display_segment_gaps: [false, true],
    display_segment_kinds: ['mixed', 'digit'],
    letters: ['ABC'],
    numbers: ['777', '777'],
    plate_type: 'STANDARD',
    kind: 'VEHICLE_PLATE',
    rarity: 'MYTHIC',
    rarity_score: 480,
    rarity_color: '#f43f5e',
    reasons: ['all_same', 'four_of_kind'],
    reason_labels: ['All Same', 'Four of a Kind'],
    traits: ['all_same', 'four_of_kind'],
    tags: ['special'],
    story: 'Every digit repeats - the purest form of plate repetition.',
    collector_bio: null,
    reel_alphabets: { letters: 'АВЕКМНОРСТУХ', digits: '0123456789' },
    is_secret: false,
    season_code: null,
    discovery_count: 3,
    first_discovered_at: '2026-01-01T00:00:00Z',
    first_discoverer: null,
    collector_value: 25000,
    currency_code: 'RUB',
    currency_symbol: '₽',
    dealer_value: 12500,
    country: { code: 'RUS', name_en: 'Russia', name_ru: 'Россия', flag: '🇷🇺' },
    region: { code: 'MOW', name_en: 'Moscow', name_ru: 'Москва' },
    template: { code: 'RUS_STD', pattern: 'LDDDLLLDD' },
    visual: ruVisual,
    owned: true,
    duplicate_count: 2,
    copies_sold: 0,
    is_favorite: false,
    is_new: false,
    sale_value: 2750,
    acquired_at: '2026-01-01T00:00:00Z',
    details: null,
    ...overrides,
  };
}

/** A collectible with no duplicates: the state where SELL must not be offered. */
export function uniquePlate(overrides: Partial<PlateCard> = {}): PlateCard {
  return plate({ duplicate_count: 0, ...overrides });
}

/** A SIM card collectible, as a real Russian provider card would arrive. */
export function simPlate(overrides: Partial<PlateCard> = {}): PlateCard {
  const details = simDetails(overrides.details ?? {});
  return plate({
    plate_text: details.synthetic_number,
    normalized_text: '79001234567',
    display_segments: ['+7 900 123 45 67'],
    display_segment_gaps: [false],
    display_segment_kinds: ['mixed'],
    plate_type: 'SIM',
    kind: 'SIM_CARD',
    country: { code: 'RUS', name_en: 'Russia', name_ru: 'Россия', flag: '🇷🇺' },
    region: null,
    template: { code: 'rus_sim_mts_apex_1', pattern: '+7 900 DDD DDD DD DD' },
    details,
    ...overrides,
  });
}

export function rollBalance(overrides: Partial<RollBalance> = {}): RollBalance {
  return {
    rolls_remaining: 18,
    normal_rolls: 18,
    bonus_rolls: 0,
    daily_allowance: 20,
    bank_cap: 20,
    resets_at: '2026-01-02T00:00:00+00:00',
    next_roll_at: null,
    seconds_to_next_roll: 0,
    regen_minutes: 45,
    ...overrides,
  };
}

export function nextTarget(overrides: Partial<NextTarget> = {}): NextTarget {
  return {
    code: 'country_region',
    country_code: 'RUS',
    country_name_en: 'Russia',
    country_name_ru: 'Россия',
    country_flag: '🇷🇺',
    current: 3,
    target: 13,
    remaining: 10,
    progress: 0.23,
    section_code: 'REGIONAL',
    section_name_en: 'Regional',
    section_name_ru: 'Региональные',
    mission_code: null,
    album_code: null,
    rarity: null,
    achievement_code: null,
    reward_coins: 0,
    providers_total: 0,
    ...overrides,
  };
}

export function rollResult(overrides: Partial<PlateRollResult> = {}): PlateRollResult {
  const card = overrides.plate ?? plate();
  return {
    success: true,
    roll_id: 99,
    plate: card,
    rarity: card.rarity,
    natural_rarity: card.rarity,
    luck_rarity: 'COMMON',
    rarity_score: card.rarity_score,
    is_duplicate: false,
    is_first_discovery: true,
    is_new_country: false,
    is_new_region: false,
    numora_awarded: 0,
    balance: 500,
    rolls_remaining: 18,
    sale_value: 2750,
    collector_level: 3,
    rolls: rollBalance({ rolls_remaining: 18, normal_rolls: 18 }),
    next_target: nextTarget(),
    missions_completed: [],
    albums_completed: [],
    unlocked_achievements: [],
    event: null,
    replayed: false,
    share_start_param: `plate_${card.id}`,
    value: card.dealer_value,
    coins_awarded: 0,
    conversion_value: card.dealer_value,
    number: card,
    ...overrides,
  };
}

export function garage(overrides: Partial<GarageData> = {}): GarageData {
  const card = overrides.recent ?? plate();
  return {
    best: card,
    recent: card,
    plates_count: 3,
    countries_count: 2,
    regions_count: 2,
    first_discoveries: 1,
    best_collector_value: 90000,
    world_progress: 0.01,
    collection_target: 10000,
    playable_countries: 30,
    locked_countries: 220,
    total_dealer_value: 40000,
    level: {
      level: 2,
      title_en: 'Spotter',
      title_ru: 'Разведчик',
      xp: 120,
      xp_into_level: 20,
      xp_for_level: 100,
      progress: 0.2,
    },
    event: null,
    albums_completed: [],
    equipped_cosmetics: [],
    hunt_country: 'RUS',
    hunt_country_name_en: 'Russia',
    hunt_country_name_ru: 'Россия',
    hunt_country_flag: '🇷🇺',
    country_progress: null,
    next_target: nextTarget(),
    rolls: rollBalance(),
    ...overrides,
  };
}

export function countryCard(overrides: Partial<CountryCard> = {}): CountryCard {
  return {
    code: 'POL',
    iso_alpha2: 'PL',
    name_en: 'Poland',
    name_ru: 'Польша',
    flag: '🇵🇱',
    region_group: 'EUROPE',
    currency_code: 'PLN',
    currency_symbol: 'zł',
    calling_code: '+48',
    visual: polVisual,
    collected: 4,
    total: 60,
    progress: 0.066,
    percent: 6.6,
    best_rarity: 'RARE',
    regions_collected: 2,
    regions_total: 6,
    completed: false,
    sort_order: 13,
    is_active: true,
    is_playable: true,
    is_active_country: true,
    regions: [
      { code: 'MZ', name_en: 'Mazovia', name_ru: 'Мазовия' },
      { code: 'SL', name_en: 'Silesia', name_ru: 'Силезия' },
    ],
    sim: {
      calling_code: '+48',
      groups: [3, 3, 3],
      providers: [
        {
          code: 'orange_pl',
          brand: 'Orange',
          local_name: 'Orange',
          rarity_modifier: 1.05,
          value_modifier: 1.08,
          visual: 'waveform',
          accent: '#ff7900',
          is_real_brand: true,
        },
        {
          code: 'play_pl',
          brand: 'Play',
          local_name: 'Play',
          rarity_modifier: 1.03,
          value_modifier: 1.05,
          visual: 'burst',
          accent: '#7b2d8e',
          is_real_brand: true,
        },
      ],
      // Derived from the same catalogue, for clients built against the old key.
      operators: [
        { code: 'orange_pl', name: 'Orange', name_local: 'Orange' },
        { code: 'play_pl', name: 'Play', name_local: 'Play' },
      ],
      editions: ['ORIGIN', 'SIGNAL', 'PULSE', 'APEX', 'CROWN'],
      synthetic: true,
    },
    completion: {
      country_code: 'POL',
      sections: [
        {
          code: 'STANDARD',
          name_en: 'Standard',
          name_ru: 'Стандарт',
          collected: 4,
          total: 24,
          remaining: 20,
          progress: 0.167,
          completed: false,
        },
        {
          code: 'REGIONAL',
          name_en: 'Regional',
          name_ru: 'Региональные',
          collected: 2,
          total: 6,
          remaining: 4,
          progress: 0.333,
          completed: false,
        },
        {
          code: 'RARE_FORMATS',
          name_en: 'Rare Formats',
          name_ru: 'Редкие форматы',
          collected: 1,
          total: 8,
          remaining: 7,
          progress: 0.125,
          completed: false,
        },
        {
          code: 'SPECIAL',
          name_en: 'Special',
          name_ru: 'Специальные',
          collected: 0,
          total: 4,
          remaining: 4,
          progress: 0,
          completed: false,
        },
      ],
      collected: 7,
      total: 42,
      remaining: 35,
      progress: 0.167,
      completed: false,
    },
    next_target: nextTarget({ country_code: 'POL', country_flag: '🇵🇱' }),
    ...overrides,
  };
}

export const profile: UserProfile = {
  id: 1,
  telegram_id: 42,
  username: 'tester',
  first_name: 'Test',
  last_name: '',
  display_name: 'Test',
  photo_url: null,
  language_code: 'en',
  role: 'USER',
  is_admin: false,
  is_banned: false,
  coins: 500,
  total_earned: 500,
  total_spent: 0,
  total_rolls: 3,
  containers_opened: 0,
  unique_numbers: 3,
  plates_count: 3,
  countries_count: 2,
  regions_count: 2,
  first_discoveries_count: 1,
  duplicates_sold_count: 0,
  collection_progress: 0.0003,
  collection_target: 10000,
  collector_level: {
    level: 2,
    title_en: 'Spotter',
    title_ru: 'Разведчик',
    xp: 120,
    xp_into_level: 20,
    xp_for_level: 100,
    progress: 0.2,
  },
  best_value: 1200,
  best_rarity: 'RARE',
  best_collector_value: 45000,
  best_plate_id: 7,
  best_plate_text: 'A123BC 777',
  referrals_count: 0,
  shares_count: 0,
  challenges_completed: 0,
  current_streak: 2,
  longest_streak: 2,
  rolls_remaining: 18,
  daily_allowance: 20,
  daily_resets_at: null,
  can_claim_daily: false,
  premium: { active: false, tier: null, expires_at: null, perks: [] },
  supporter: false,
  season_pass_active: false,
  equipped_title: null,
  equipped_cosmetics: [],
  created_at: '2026-01-01T00:00:00Z',
  last_seen_at: null,
};

export const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
